// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/FindHotel/shortcut-go/models"
)

// CreateStoryReader is a Reader for the CreateStory structure.
type CreateStoryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateStoryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateStoryCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateStoryBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewCreateStoryNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewCreateStoryUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateStoryCreated creates a CreateStoryCreated with default headers values
func NewCreateStoryCreated() *CreateStoryCreated {
	return &CreateStoryCreated{}
}

/*
CreateStoryCreated describes a response with status code 201, with default header values.

Resource
*/
type CreateStoryCreated struct {
	Payload *models.Story
}

// IsSuccess returns true when this create story created response has a 2xx status code
func (o *CreateStoryCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create story created response has a 3xx status code
func (o *CreateStoryCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create story created response has a 4xx status code
func (o *CreateStoryCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this create story created response has a 5xx status code
func (o *CreateStoryCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this create story created response a status code equal to that given
func (o *CreateStoryCreated) IsCode(code int) bool {
	return code == 201
}

func (o *CreateStoryCreated) Error() string {
	return fmt.Sprintf("[POST /api/v3/stories][%d] createStoryCreated  %+v", 201, o.Payload)
}

func (o *CreateStoryCreated) String() string {
	return fmt.Sprintf("[POST /api/v3/stories][%d] createStoryCreated  %+v", 201, o.Payload)
}

func (o *CreateStoryCreated) GetPayload() *models.Story {
	return o.Payload
}

func (o *CreateStoryCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Story)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateStoryBadRequest creates a CreateStoryBadRequest with default headers values
func NewCreateStoryBadRequest() *CreateStoryBadRequest {
	return &CreateStoryBadRequest{}
}

/*
CreateStoryBadRequest describes a response with status code 400, with default header values.

Schema mismatch
*/
type CreateStoryBadRequest struct {
}

// IsSuccess returns true when this create story bad request response has a 2xx status code
func (o *CreateStoryBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create story bad request response has a 3xx status code
func (o *CreateStoryBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create story bad request response has a 4xx status code
func (o *CreateStoryBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this create story bad request response has a 5xx status code
func (o *CreateStoryBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this create story bad request response a status code equal to that given
func (o *CreateStoryBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *CreateStoryBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/v3/stories][%d] createStoryBadRequest ", 400)
}

func (o *CreateStoryBadRequest) String() string {
	return fmt.Sprintf("[POST /api/v3/stories][%d] createStoryBadRequest ", 400)
}

func (o *CreateStoryBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateStoryNotFound creates a CreateStoryNotFound with default headers values
func NewCreateStoryNotFound() *CreateStoryNotFound {
	return &CreateStoryNotFound{}
}

/*
CreateStoryNotFound describes a response with status code 404, with default header values.

Resource does not exist
*/
type CreateStoryNotFound struct {
}

// IsSuccess returns true when this create story not found response has a 2xx status code
func (o *CreateStoryNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create story not found response has a 3xx status code
func (o *CreateStoryNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create story not found response has a 4xx status code
func (o *CreateStoryNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this create story not found response has a 5xx status code
func (o *CreateStoryNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this create story not found response a status code equal to that given
func (o *CreateStoryNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *CreateStoryNotFound) Error() string {
	return fmt.Sprintf("[POST /api/v3/stories][%d] createStoryNotFound ", 404)
}

func (o *CreateStoryNotFound) String() string {
	return fmt.Sprintf("[POST /api/v3/stories][%d] createStoryNotFound ", 404)
}

func (o *CreateStoryNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateStoryUnprocessableEntity creates a CreateStoryUnprocessableEntity with default headers values
func NewCreateStoryUnprocessableEntity() *CreateStoryUnprocessableEntity {
	return &CreateStoryUnprocessableEntity{}
}

/*
CreateStoryUnprocessableEntity describes a response with status code 422, with default header values.

Unprocessable
*/
type CreateStoryUnprocessableEntity struct {
}

// IsSuccess returns true when this create story unprocessable entity response has a 2xx status code
func (o *CreateStoryUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create story unprocessable entity response has a 3xx status code
func (o *CreateStoryUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create story unprocessable entity response has a 4xx status code
func (o *CreateStoryUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this create story unprocessable entity response has a 5xx status code
func (o *CreateStoryUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this create story unprocessable entity response a status code equal to that given
func (o *CreateStoryUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

func (o *CreateStoryUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /api/v3/stories][%d] createStoryUnprocessableEntity ", 422)
}

func (o *CreateStoryUnprocessableEntity) String() string {
	return fmt.Sprintf("[POST /api/v3/stories][%d] createStoryUnprocessableEntity ", 422)
}

func (o *CreateStoryUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
