// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/FindHotel/shortcut-go/models"
)

// CreateGroupReader is a Reader for the CreateGroup structure.
type CreateGroupReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateGroupReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateGroupCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateGroupBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewCreateGroupForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewCreateGroupNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewCreateGroupUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateGroupCreated creates a CreateGroupCreated with default headers values
func NewCreateGroupCreated() *CreateGroupCreated {
	return &CreateGroupCreated{}
}

/*
CreateGroupCreated describes a response with status code 201, with default header values.

Resource
*/
type CreateGroupCreated struct {
	Payload *models.Group
}

// IsSuccess returns true when this create group created response has a 2xx status code
func (o *CreateGroupCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create group created response has a 3xx status code
func (o *CreateGroupCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create group created response has a 4xx status code
func (o *CreateGroupCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this create group created response has a 5xx status code
func (o *CreateGroupCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this create group created response a status code equal to that given
func (o *CreateGroupCreated) IsCode(code int) bool {
	return code == 201
}

func (o *CreateGroupCreated) Error() string {
	return fmt.Sprintf("[POST /api/v3/groups][%d] createGroupCreated  %+v", 201, o.Payload)
}

func (o *CreateGroupCreated) String() string {
	return fmt.Sprintf("[POST /api/v3/groups][%d] createGroupCreated  %+v", 201, o.Payload)
}

func (o *CreateGroupCreated) GetPayload() *models.Group {
	return o.Payload
}

func (o *CreateGroupCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Group)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateGroupBadRequest creates a CreateGroupBadRequest with default headers values
func NewCreateGroupBadRequest() *CreateGroupBadRequest {
	return &CreateGroupBadRequest{}
}

/*
CreateGroupBadRequest describes a response with status code 400, with default header values.

Schema mismatch
*/
type CreateGroupBadRequest struct {
}

// IsSuccess returns true when this create group bad request response has a 2xx status code
func (o *CreateGroupBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create group bad request response has a 3xx status code
func (o *CreateGroupBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create group bad request response has a 4xx status code
func (o *CreateGroupBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this create group bad request response has a 5xx status code
func (o *CreateGroupBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this create group bad request response a status code equal to that given
func (o *CreateGroupBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *CreateGroupBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/v3/groups][%d] createGroupBadRequest ", 400)
}

func (o *CreateGroupBadRequest) String() string {
	return fmt.Sprintf("[POST /api/v3/groups][%d] createGroupBadRequest ", 400)
}

func (o *CreateGroupBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateGroupForbidden creates a CreateGroupForbidden with default headers values
func NewCreateGroupForbidden() *CreateGroupForbidden {
	return &CreateGroupForbidden{}
}

/*
CreateGroupForbidden describes a response with status code 403, with default header values.

CreateGroupForbidden create group forbidden
*/
type CreateGroupForbidden struct {
	Payload *models.UnusableEntitlementError
}

// IsSuccess returns true when this create group forbidden response has a 2xx status code
func (o *CreateGroupForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create group forbidden response has a 3xx status code
func (o *CreateGroupForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create group forbidden response has a 4xx status code
func (o *CreateGroupForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this create group forbidden response has a 5xx status code
func (o *CreateGroupForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this create group forbidden response a status code equal to that given
func (o *CreateGroupForbidden) IsCode(code int) bool {
	return code == 403
}

func (o *CreateGroupForbidden) Error() string {
	return fmt.Sprintf("[POST /api/v3/groups][%d] createGroupForbidden  %+v", 403, o.Payload)
}

func (o *CreateGroupForbidden) String() string {
	return fmt.Sprintf("[POST /api/v3/groups][%d] createGroupForbidden  %+v", 403, o.Payload)
}

func (o *CreateGroupForbidden) GetPayload() *models.UnusableEntitlementError {
	return o.Payload
}

func (o *CreateGroupForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UnusableEntitlementError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateGroupNotFound creates a CreateGroupNotFound with default headers values
func NewCreateGroupNotFound() *CreateGroupNotFound {
	return &CreateGroupNotFound{}
}

/*
CreateGroupNotFound describes a response with status code 404, with default header values.

Resource does not exist
*/
type CreateGroupNotFound struct {
}

// IsSuccess returns true when this create group not found response has a 2xx status code
func (o *CreateGroupNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create group not found response has a 3xx status code
func (o *CreateGroupNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create group not found response has a 4xx status code
func (o *CreateGroupNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this create group not found response has a 5xx status code
func (o *CreateGroupNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this create group not found response a status code equal to that given
func (o *CreateGroupNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *CreateGroupNotFound) Error() string {
	return fmt.Sprintf("[POST /api/v3/groups][%d] createGroupNotFound ", 404)
}

func (o *CreateGroupNotFound) String() string {
	return fmt.Sprintf("[POST /api/v3/groups][%d] createGroupNotFound ", 404)
}

func (o *CreateGroupNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateGroupUnprocessableEntity creates a CreateGroupUnprocessableEntity with default headers values
func NewCreateGroupUnprocessableEntity() *CreateGroupUnprocessableEntity {
	return &CreateGroupUnprocessableEntity{}
}

/*
CreateGroupUnprocessableEntity describes a response with status code 422, with default header values.

Unprocessable
*/
type CreateGroupUnprocessableEntity struct {
}

// IsSuccess returns true when this create group unprocessable entity response has a 2xx status code
func (o *CreateGroupUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create group unprocessable entity response has a 3xx status code
func (o *CreateGroupUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create group unprocessable entity response has a 4xx status code
func (o *CreateGroupUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this create group unprocessable entity response has a 5xx status code
func (o *CreateGroupUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this create group unprocessable entity response a status code equal to that given
func (o *CreateGroupUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

func (o *CreateGroupUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /api/v3/groups][%d] createGroupUnprocessableEntity ", 422)
}

func (o *CreateGroupUnprocessableEntity) String() string {
	return fmt.Sprintf("[POST /api/v3/groups][%d] createGroupUnprocessableEntity ", 422)
}

func (o *CreateGroupUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
