// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/FindHotel/shortcut-go/models"
)

// CreateStoryReactionReader is a Reader for the CreateStoryReaction structure.
type CreateStoryReactionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateStoryReactionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateStoryReactionCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateStoryReactionBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewCreateStoryReactionNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewCreateStoryReactionUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateStoryReactionCreated creates a CreateStoryReactionCreated with default headers values
func NewCreateStoryReactionCreated() *CreateStoryReactionCreated {
	return &CreateStoryReactionCreated{}
}

/*
CreateStoryReactionCreated describes a response with status code 201, with default header values.

Resource
*/
type CreateStoryReactionCreated struct {
	Payload []*models.StoryReaction
}

// IsSuccess returns true when this create story reaction created response has a 2xx status code
func (o *CreateStoryReactionCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create story reaction created response has a 3xx status code
func (o *CreateStoryReactionCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create story reaction created response has a 4xx status code
func (o *CreateStoryReactionCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this create story reaction created response has a 5xx status code
func (o *CreateStoryReactionCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this create story reaction created response a status code equal to that given
func (o *CreateStoryReactionCreated) IsCode(code int) bool {
	return code == 201
}

func (o *CreateStoryReactionCreated) Error() string {
	return fmt.Sprintf("[POST /api/v3/stories/{story-public-id}/comments/{comment-public-id}/reactions][%d] createStoryReactionCreated  %+v", 201, o.Payload)
}

func (o *CreateStoryReactionCreated) String() string {
	return fmt.Sprintf("[POST /api/v3/stories/{story-public-id}/comments/{comment-public-id}/reactions][%d] createStoryReactionCreated  %+v", 201, o.Payload)
}

func (o *CreateStoryReactionCreated) GetPayload() []*models.StoryReaction {
	return o.Payload
}

func (o *CreateStoryReactionCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateStoryReactionBadRequest creates a CreateStoryReactionBadRequest with default headers values
func NewCreateStoryReactionBadRequest() *CreateStoryReactionBadRequest {
	return &CreateStoryReactionBadRequest{}
}

/*
CreateStoryReactionBadRequest describes a response with status code 400, with default header values.

Schema mismatch
*/
type CreateStoryReactionBadRequest struct {
}

// IsSuccess returns true when this create story reaction bad request response has a 2xx status code
func (o *CreateStoryReactionBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create story reaction bad request response has a 3xx status code
func (o *CreateStoryReactionBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create story reaction bad request response has a 4xx status code
func (o *CreateStoryReactionBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this create story reaction bad request response has a 5xx status code
func (o *CreateStoryReactionBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this create story reaction bad request response a status code equal to that given
func (o *CreateStoryReactionBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *CreateStoryReactionBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/v3/stories/{story-public-id}/comments/{comment-public-id}/reactions][%d] createStoryReactionBadRequest ", 400)
}

func (o *CreateStoryReactionBadRequest) String() string {
	return fmt.Sprintf("[POST /api/v3/stories/{story-public-id}/comments/{comment-public-id}/reactions][%d] createStoryReactionBadRequest ", 400)
}

func (o *CreateStoryReactionBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateStoryReactionNotFound creates a CreateStoryReactionNotFound with default headers values
func NewCreateStoryReactionNotFound() *CreateStoryReactionNotFound {
	return &CreateStoryReactionNotFound{}
}

/*
CreateStoryReactionNotFound describes a response with status code 404, with default header values.

Resource does not exist
*/
type CreateStoryReactionNotFound struct {
}

// IsSuccess returns true when this create story reaction not found response has a 2xx status code
func (o *CreateStoryReactionNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create story reaction not found response has a 3xx status code
func (o *CreateStoryReactionNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create story reaction not found response has a 4xx status code
func (o *CreateStoryReactionNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this create story reaction not found response has a 5xx status code
func (o *CreateStoryReactionNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this create story reaction not found response a status code equal to that given
func (o *CreateStoryReactionNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *CreateStoryReactionNotFound) Error() string {
	return fmt.Sprintf("[POST /api/v3/stories/{story-public-id}/comments/{comment-public-id}/reactions][%d] createStoryReactionNotFound ", 404)
}

func (o *CreateStoryReactionNotFound) String() string {
	return fmt.Sprintf("[POST /api/v3/stories/{story-public-id}/comments/{comment-public-id}/reactions][%d] createStoryReactionNotFound ", 404)
}

func (o *CreateStoryReactionNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateStoryReactionUnprocessableEntity creates a CreateStoryReactionUnprocessableEntity with default headers values
func NewCreateStoryReactionUnprocessableEntity() *CreateStoryReactionUnprocessableEntity {
	return &CreateStoryReactionUnprocessableEntity{}
}

/*
CreateStoryReactionUnprocessableEntity describes a response with status code 422, with default header values.

Unprocessable
*/
type CreateStoryReactionUnprocessableEntity struct {
}

// IsSuccess returns true when this create story reaction unprocessable entity response has a 2xx status code
func (o *CreateStoryReactionUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create story reaction unprocessable entity response has a 3xx status code
func (o *CreateStoryReactionUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create story reaction unprocessable entity response has a 4xx status code
func (o *CreateStoryReactionUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this create story reaction unprocessable entity response has a 5xx status code
func (o *CreateStoryReactionUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this create story reaction unprocessable entity response a status code equal to that given
func (o *CreateStoryReactionUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

func (o *CreateStoryReactionUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /api/v3/stories/{story-public-id}/comments/{comment-public-id}/reactions][%d] createStoryReactionUnprocessableEntity ", 422)
}

func (o *CreateStoryReactionUnprocessableEntity) String() string {
	return fmt.Sprintf("[POST /api/v3/stories/{story-public-id}/comments/{comment-public-id}/reactions][%d] createStoryReactionUnprocessableEntity ", 422)
}

func (o *CreateStoryReactionUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
