// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/FindHotel/shortcut-go/models"
)

// CreateEpicReader is a Reader for the CreateEpic structure.
type CreateEpicReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateEpicReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateEpicCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateEpicBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewCreateEpicNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewCreateEpicUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /api/v3/epics] createEpic", response, response.Code())
	}
}

// NewCreateEpicCreated creates a CreateEpicCreated with default headers values
func NewCreateEpicCreated() *CreateEpicCreated {
	return &CreateEpicCreated{}
}

/*
CreateEpicCreated describes a response with status code 201, with default header values.

Resource
*/
type CreateEpicCreated struct {
	Payload *models.Epic
}

// IsSuccess returns true when this create epic created response has a 2xx status code
func (o *CreateEpicCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create epic created response has a 3xx status code
func (o *CreateEpicCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create epic created response has a 4xx status code
func (o *CreateEpicCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this create epic created response has a 5xx status code
func (o *CreateEpicCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this create epic created response a status code equal to that given
func (o *CreateEpicCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the create epic created response
func (o *CreateEpicCreated) Code() int {
	return 201
}

func (o *CreateEpicCreated) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v3/epics][%d] createEpicCreated %s", 201, payload)
}

func (o *CreateEpicCreated) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v3/epics][%d] createEpicCreated %s", 201, payload)
}

func (o *CreateEpicCreated) GetPayload() *models.Epic {
	return o.Payload
}

func (o *CreateEpicCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Epic)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateEpicBadRequest creates a CreateEpicBadRequest with default headers values
func NewCreateEpicBadRequest() *CreateEpicBadRequest {
	return &CreateEpicBadRequest{}
}

/*
CreateEpicBadRequest describes a response with status code 400, with default header values.

Schema mismatch
*/
type CreateEpicBadRequest struct {
}

// IsSuccess returns true when this create epic bad request response has a 2xx status code
func (o *CreateEpicBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create epic bad request response has a 3xx status code
func (o *CreateEpicBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create epic bad request response has a 4xx status code
func (o *CreateEpicBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this create epic bad request response has a 5xx status code
func (o *CreateEpicBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this create epic bad request response a status code equal to that given
func (o *CreateEpicBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the create epic bad request response
func (o *CreateEpicBadRequest) Code() int {
	return 400
}

func (o *CreateEpicBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/v3/epics][%d] createEpicBadRequest", 400)
}

func (o *CreateEpicBadRequest) String() string {
	return fmt.Sprintf("[POST /api/v3/epics][%d] createEpicBadRequest", 400)
}

func (o *CreateEpicBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateEpicNotFound creates a CreateEpicNotFound with default headers values
func NewCreateEpicNotFound() *CreateEpicNotFound {
	return &CreateEpicNotFound{}
}

/*
CreateEpicNotFound describes a response with status code 404, with default header values.

Resource does not exist
*/
type CreateEpicNotFound struct {
}

// IsSuccess returns true when this create epic not found response has a 2xx status code
func (o *CreateEpicNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create epic not found response has a 3xx status code
func (o *CreateEpicNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create epic not found response has a 4xx status code
func (o *CreateEpicNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this create epic not found response has a 5xx status code
func (o *CreateEpicNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this create epic not found response a status code equal to that given
func (o *CreateEpicNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the create epic not found response
func (o *CreateEpicNotFound) Code() int {
	return 404
}

func (o *CreateEpicNotFound) Error() string {
	return fmt.Sprintf("[POST /api/v3/epics][%d] createEpicNotFound", 404)
}

func (o *CreateEpicNotFound) String() string {
	return fmt.Sprintf("[POST /api/v3/epics][%d] createEpicNotFound", 404)
}

func (o *CreateEpicNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateEpicUnprocessableEntity creates a CreateEpicUnprocessableEntity with default headers values
func NewCreateEpicUnprocessableEntity() *CreateEpicUnprocessableEntity {
	return &CreateEpicUnprocessableEntity{}
}

/*
CreateEpicUnprocessableEntity describes a response with status code 422, with default header values.

Unprocessable
*/
type CreateEpicUnprocessableEntity struct {
}

// IsSuccess returns true when this create epic unprocessable entity response has a 2xx status code
func (o *CreateEpicUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create epic unprocessable entity response has a 3xx status code
func (o *CreateEpicUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create epic unprocessable entity response has a 4xx status code
func (o *CreateEpicUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this create epic unprocessable entity response has a 5xx status code
func (o *CreateEpicUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this create epic unprocessable entity response a status code equal to that given
func (o *CreateEpicUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

// Code gets the status code for the create epic unprocessable entity response
func (o *CreateEpicUnprocessableEntity) Code() int {
	return 422
}

func (o *CreateEpicUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /api/v3/epics][%d] createEpicUnprocessableEntity", 422)
}

func (o *CreateEpicUnprocessableEntity) String() string {
	return fmt.Sprintf("[POST /api/v3/epics][%d] createEpicUnprocessableEntity", 422)
}

func (o *CreateEpicUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
