// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/FindHotel/shortcut-go/models"
)

// CreateIterationReader is a Reader for the CreateIteration structure.
type CreateIterationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateIterationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateIterationCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateIterationBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewCreateIterationNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewCreateIterationUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /api/v3/iterations] createIteration", response, response.Code())
	}
}

// NewCreateIterationCreated creates a CreateIterationCreated with default headers values
func NewCreateIterationCreated() *CreateIterationCreated {
	return &CreateIterationCreated{}
}

/*
CreateIterationCreated describes a response with status code 201, with default header values.

Resource
*/
type CreateIterationCreated struct {
	Payload *models.Iteration
}

// IsSuccess returns true when this create iteration created response has a 2xx status code
func (o *CreateIterationCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create iteration created response has a 3xx status code
func (o *CreateIterationCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create iteration created response has a 4xx status code
func (o *CreateIterationCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this create iteration created response has a 5xx status code
func (o *CreateIterationCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this create iteration created response a status code equal to that given
func (o *CreateIterationCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the create iteration created response
func (o *CreateIterationCreated) Code() int {
	return 201
}

func (o *CreateIterationCreated) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v3/iterations][%d] createIterationCreated %s", 201, payload)
}

func (o *CreateIterationCreated) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v3/iterations][%d] createIterationCreated %s", 201, payload)
}

func (o *CreateIterationCreated) GetPayload() *models.Iteration {
	return o.Payload
}

func (o *CreateIterationCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Iteration)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateIterationBadRequest creates a CreateIterationBadRequest with default headers values
func NewCreateIterationBadRequest() *CreateIterationBadRequest {
	return &CreateIterationBadRequest{}
}

/*
CreateIterationBadRequest describes a response with status code 400, with default header values.

Schema mismatch
*/
type CreateIterationBadRequest struct {
}

// IsSuccess returns true when this create iteration bad request response has a 2xx status code
func (o *CreateIterationBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create iteration bad request response has a 3xx status code
func (o *CreateIterationBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create iteration bad request response has a 4xx status code
func (o *CreateIterationBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this create iteration bad request response has a 5xx status code
func (o *CreateIterationBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this create iteration bad request response a status code equal to that given
func (o *CreateIterationBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the create iteration bad request response
func (o *CreateIterationBadRequest) Code() int {
	return 400
}

func (o *CreateIterationBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/v3/iterations][%d] createIterationBadRequest", 400)
}

func (o *CreateIterationBadRequest) String() string {
	return fmt.Sprintf("[POST /api/v3/iterations][%d] createIterationBadRequest", 400)
}

func (o *CreateIterationBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateIterationNotFound creates a CreateIterationNotFound with default headers values
func NewCreateIterationNotFound() *CreateIterationNotFound {
	return &CreateIterationNotFound{}
}

/*
CreateIterationNotFound describes a response with status code 404, with default header values.

Resource does not exist
*/
type CreateIterationNotFound struct {
}

// IsSuccess returns true when this create iteration not found response has a 2xx status code
func (o *CreateIterationNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create iteration not found response has a 3xx status code
func (o *CreateIterationNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create iteration not found response has a 4xx status code
func (o *CreateIterationNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this create iteration not found response has a 5xx status code
func (o *CreateIterationNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this create iteration not found response a status code equal to that given
func (o *CreateIterationNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the create iteration not found response
func (o *CreateIterationNotFound) Code() int {
	return 404
}

func (o *CreateIterationNotFound) Error() string {
	return fmt.Sprintf("[POST /api/v3/iterations][%d] createIterationNotFound", 404)
}

func (o *CreateIterationNotFound) String() string {
	return fmt.Sprintf("[POST /api/v3/iterations][%d] createIterationNotFound", 404)
}

func (o *CreateIterationNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateIterationUnprocessableEntity creates a CreateIterationUnprocessableEntity with default headers values
func NewCreateIterationUnprocessableEntity() *CreateIterationUnprocessableEntity {
	return &CreateIterationUnprocessableEntity{}
}

/*
CreateIterationUnprocessableEntity describes a response with status code 422, with default header values.

Unprocessable
*/
type CreateIterationUnprocessableEntity struct {
}

// IsSuccess returns true when this create iteration unprocessable entity response has a 2xx status code
func (o *CreateIterationUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create iteration unprocessable entity response has a 3xx status code
func (o *CreateIterationUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create iteration unprocessable entity response has a 4xx status code
func (o *CreateIterationUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this create iteration unprocessable entity response has a 5xx status code
func (o *CreateIterationUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this create iteration unprocessable entity response a status code equal to that given
func (o *CreateIterationUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

// Code gets the status code for the create iteration unprocessable entity response
func (o *CreateIterationUnprocessableEntity) Code() int {
	return 422
}

func (o *CreateIterationUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /api/v3/iterations][%d] createIterationUnprocessableEntity", 422)
}

func (o *CreateIterationUnprocessableEntity) String() string {
	return fmt.Sprintf("[POST /api/v3/iterations][%d] createIterationUnprocessableEntity", 422)
}

func (o *CreateIterationUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
