// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteLabelReader is a Reader for the DeleteLabel structure.
type DeleteLabelReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteLabelReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteLabelNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteLabelBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteLabelNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewDeleteLabelUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteLabelNoContent creates a DeleteLabelNoContent with default headers values
func NewDeleteLabelNoContent() *DeleteLabelNoContent {
	return &DeleteLabelNoContent{}
}

/*
DeleteLabelNoContent describes a response with status code 204, with default header values.

No Content
*/
type DeleteLabelNoContent struct {
}

// IsSuccess returns true when this delete label no content response has a 2xx status code
func (o *DeleteLabelNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete label no content response has a 3xx status code
func (o *DeleteLabelNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete label no content response has a 4xx status code
func (o *DeleteLabelNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete label no content response has a 5xx status code
func (o *DeleteLabelNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this delete label no content response a status code equal to that given
func (o *DeleteLabelNoContent) IsCode(code int) bool {
	return code == 204
}

func (o *DeleteLabelNoContent) Error() string {
	return fmt.Sprintf("[DELETE /api/v3/labels/{label-public-id}][%d] deleteLabelNoContent ", 204)
}

func (o *DeleteLabelNoContent) String() string {
	return fmt.Sprintf("[DELETE /api/v3/labels/{label-public-id}][%d] deleteLabelNoContent ", 204)
}

func (o *DeleteLabelNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteLabelBadRequest creates a DeleteLabelBadRequest with default headers values
func NewDeleteLabelBadRequest() *DeleteLabelBadRequest {
	return &DeleteLabelBadRequest{}
}

/*
DeleteLabelBadRequest describes a response with status code 400, with default header values.

Schema mismatch
*/
type DeleteLabelBadRequest struct {
}

// IsSuccess returns true when this delete label bad request response has a 2xx status code
func (o *DeleteLabelBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete label bad request response has a 3xx status code
func (o *DeleteLabelBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete label bad request response has a 4xx status code
func (o *DeleteLabelBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete label bad request response has a 5xx status code
func (o *DeleteLabelBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this delete label bad request response a status code equal to that given
func (o *DeleteLabelBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *DeleteLabelBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /api/v3/labels/{label-public-id}][%d] deleteLabelBadRequest ", 400)
}

func (o *DeleteLabelBadRequest) String() string {
	return fmt.Sprintf("[DELETE /api/v3/labels/{label-public-id}][%d] deleteLabelBadRequest ", 400)
}

func (o *DeleteLabelBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteLabelNotFound creates a DeleteLabelNotFound with default headers values
func NewDeleteLabelNotFound() *DeleteLabelNotFound {
	return &DeleteLabelNotFound{}
}

/*
DeleteLabelNotFound describes a response with status code 404, with default header values.

Resource does not exist
*/
type DeleteLabelNotFound struct {
}

// IsSuccess returns true when this delete label not found response has a 2xx status code
func (o *DeleteLabelNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete label not found response has a 3xx status code
func (o *DeleteLabelNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete label not found response has a 4xx status code
func (o *DeleteLabelNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete label not found response has a 5xx status code
func (o *DeleteLabelNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this delete label not found response a status code equal to that given
func (o *DeleteLabelNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *DeleteLabelNotFound) Error() string {
	return fmt.Sprintf("[DELETE /api/v3/labels/{label-public-id}][%d] deleteLabelNotFound ", 404)
}

func (o *DeleteLabelNotFound) String() string {
	return fmt.Sprintf("[DELETE /api/v3/labels/{label-public-id}][%d] deleteLabelNotFound ", 404)
}

func (o *DeleteLabelNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteLabelUnprocessableEntity creates a DeleteLabelUnprocessableEntity with default headers values
func NewDeleteLabelUnprocessableEntity() *DeleteLabelUnprocessableEntity {
	return &DeleteLabelUnprocessableEntity{}
}

/*
DeleteLabelUnprocessableEntity describes a response with status code 422, with default header values.

Unprocessable
*/
type DeleteLabelUnprocessableEntity struct {
}

// IsSuccess returns true when this delete label unprocessable entity response has a 2xx status code
func (o *DeleteLabelUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete label unprocessable entity response has a 3xx status code
func (o *DeleteLabelUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete label unprocessable entity response has a 4xx status code
func (o *DeleteLabelUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete label unprocessable entity response has a 5xx status code
func (o *DeleteLabelUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this delete label unprocessable entity response a status code equal to that given
func (o *DeleteLabelUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

func (o *DeleteLabelUnprocessableEntity) Error() string {
	return fmt.Sprintf("[DELETE /api/v3/labels/{label-public-id}][%d] deleteLabelUnprocessableEntity ", 422)
}

func (o *DeleteLabelUnprocessableEntity) String() string {
	return fmt.Sprintf("[DELETE /api/v3/labels/{label-public-id}][%d] deleteLabelUnprocessableEntity ", 422)
}

func (o *DeleteLabelUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
