// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteStoryReader is a Reader for the DeleteStory structure.
type DeleteStoryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteStoryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteStoryNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteStoryBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteStoryNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewDeleteStoryUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteStoryNoContent creates a DeleteStoryNoContent with default headers values
func NewDeleteStoryNoContent() *DeleteStoryNoContent {
	return &DeleteStoryNoContent{}
}

/*
DeleteStoryNoContent describes a response with status code 204, with default header values.

No Content
*/
type DeleteStoryNoContent struct {
}

// IsSuccess returns true when this delete story no content response has a 2xx status code
func (o *DeleteStoryNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete story no content response has a 3xx status code
func (o *DeleteStoryNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete story no content response has a 4xx status code
func (o *DeleteStoryNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete story no content response has a 5xx status code
func (o *DeleteStoryNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this delete story no content response a status code equal to that given
func (o *DeleteStoryNoContent) IsCode(code int) bool {
	return code == 204
}

func (o *DeleteStoryNoContent) Error() string {
	return fmt.Sprintf("[DELETE /api/v3/stories/{story-public-id}][%d] deleteStoryNoContent ", 204)
}

func (o *DeleteStoryNoContent) String() string {
	return fmt.Sprintf("[DELETE /api/v3/stories/{story-public-id}][%d] deleteStoryNoContent ", 204)
}

func (o *DeleteStoryNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteStoryBadRequest creates a DeleteStoryBadRequest with default headers values
func NewDeleteStoryBadRequest() *DeleteStoryBadRequest {
	return &DeleteStoryBadRequest{}
}

/*
DeleteStoryBadRequest describes a response with status code 400, with default header values.

Schema mismatch
*/
type DeleteStoryBadRequest struct {
}

// IsSuccess returns true when this delete story bad request response has a 2xx status code
func (o *DeleteStoryBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete story bad request response has a 3xx status code
func (o *DeleteStoryBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete story bad request response has a 4xx status code
func (o *DeleteStoryBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete story bad request response has a 5xx status code
func (o *DeleteStoryBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this delete story bad request response a status code equal to that given
func (o *DeleteStoryBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *DeleteStoryBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /api/v3/stories/{story-public-id}][%d] deleteStoryBadRequest ", 400)
}

func (o *DeleteStoryBadRequest) String() string {
	return fmt.Sprintf("[DELETE /api/v3/stories/{story-public-id}][%d] deleteStoryBadRequest ", 400)
}

func (o *DeleteStoryBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteStoryNotFound creates a DeleteStoryNotFound with default headers values
func NewDeleteStoryNotFound() *DeleteStoryNotFound {
	return &DeleteStoryNotFound{}
}

/*
DeleteStoryNotFound describes a response with status code 404, with default header values.

Resource does not exist
*/
type DeleteStoryNotFound struct {
}

// IsSuccess returns true when this delete story not found response has a 2xx status code
func (o *DeleteStoryNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete story not found response has a 3xx status code
func (o *DeleteStoryNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete story not found response has a 4xx status code
func (o *DeleteStoryNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete story not found response has a 5xx status code
func (o *DeleteStoryNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this delete story not found response a status code equal to that given
func (o *DeleteStoryNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *DeleteStoryNotFound) Error() string {
	return fmt.Sprintf("[DELETE /api/v3/stories/{story-public-id}][%d] deleteStoryNotFound ", 404)
}

func (o *DeleteStoryNotFound) String() string {
	return fmt.Sprintf("[DELETE /api/v3/stories/{story-public-id}][%d] deleteStoryNotFound ", 404)
}

func (o *DeleteStoryNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteStoryUnprocessableEntity creates a DeleteStoryUnprocessableEntity with default headers values
func NewDeleteStoryUnprocessableEntity() *DeleteStoryUnprocessableEntity {
	return &DeleteStoryUnprocessableEntity{}
}

/*
DeleteStoryUnprocessableEntity describes a response with status code 422, with default header values.

Unprocessable
*/
type DeleteStoryUnprocessableEntity struct {
}

// IsSuccess returns true when this delete story unprocessable entity response has a 2xx status code
func (o *DeleteStoryUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete story unprocessable entity response has a 3xx status code
func (o *DeleteStoryUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete story unprocessable entity response has a 4xx status code
func (o *DeleteStoryUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete story unprocessable entity response has a 5xx status code
func (o *DeleteStoryUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this delete story unprocessable entity response a status code equal to that given
func (o *DeleteStoryUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

func (o *DeleteStoryUnprocessableEntity) Error() string {
	return fmt.Sprintf("[DELETE /api/v3/stories/{story-public-id}][%d] deleteStoryUnprocessableEntity ", 422)
}

func (o *DeleteStoryUnprocessableEntity) String() string {
	return fmt.Sprintf("[DELETE /api/v3/stories/{story-public-id}][%d] deleteStoryUnprocessableEntity ", 422)
}

func (o *DeleteStoryUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
