// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteMilestoneReader is a Reader for the DeleteMilestone structure.
type DeleteMilestoneReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteMilestoneReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteMilestoneNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteMilestoneBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteMilestoneNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewDeleteMilestoneUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /api/v3/milestones/{milestone-public-id}] deleteMilestone", response, response.Code())
	}
}

// NewDeleteMilestoneNoContent creates a DeleteMilestoneNoContent with default headers values
func NewDeleteMilestoneNoContent() *DeleteMilestoneNoContent {
	return &DeleteMilestoneNoContent{}
}

/*
DeleteMilestoneNoContent describes a response with status code 204, with default header values.

No Content
*/
type DeleteMilestoneNoContent struct {
}

// IsSuccess returns true when this delete milestone no content response has a 2xx status code
func (o *DeleteMilestoneNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete milestone no content response has a 3xx status code
func (o *DeleteMilestoneNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete milestone no content response has a 4xx status code
func (o *DeleteMilestoneNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete milestone no content response has a 5xx status code
func (o *DeleteMilestoneNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this delete milestone no content response a status code equal to that given
func (o *DeleteMilestoneNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the delete milestone no content response
func (o *DeleteMilestoneNoContent) Code() int {
	return 204
}

func (o *DeleteMilestoneNoContent) Error() string {
	return fmt.Sprintf("[DELETE /api/v3/milestones/{milestone-public-id}][%d] deleteMilestoneNoContent", 204)
}

func (o *DeleteMilestoneNoContent) String() string {
	return fmt.Sprintf("[DELETE /api/v3/milestones/{milestone-public-id}][%d] deleteMilestoneNoContent", 204)
}

func (o *DeleteMilestoneNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteMilestoneBadRequest creates a DeleteMilestoneBadRequest with default headers values
func NewDeleteMilestoneBadRequest() *DeleteMilestoneBadRequest {
	return &DeleteMilestoneBadRequest{}
}

/*
DeleteMilestoneBadRequest describes a response with status code 400, with default header values.

Schema mismatch
*/
type DeleteMilestoneBadRequest struct {
}

// IsSuccess returns true when this delete milestone bad request response has a 2xx status code
func (o *DeleteMilestoneBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete milestone bad request response has a 3xx status code
func (o *DeleteMilestoneBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete milestone bad request response has a 4xx status code
func (o *DeleteMilestoneBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete milestone bad request response has a 5xx status code
func (o *DeleteMilestoneBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this delete milestone bad request response a status code equal to that given
func (o *DeleteMilestoneBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the delete milestone bad request response
func (o *DeleteMilestoneBadRequest) Code() int {
	return 400
}

func (o *DeleteMilestoneBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /api/v3/milestones/{milestone-public-id}][%d] deleteMilestoneBadRequest", 400)
}

func (o *DeleteMilestoneBadRequest) String() string {
	return fmt.Sprintf("[DELETE /api/v3/milestones/{milestone-public-id}][%d] deleteMilestoneBadRequest", 400)
}

func (o *DeleteMilestoneBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteMilestoneNotFound creates a DeleteMilestoneNotFound with default headers values
func NewDeleteMilestoneNotFound() *DeleteMilestoneNotFound {
	return &DeleteMilestoneNotFound{}
}

/*
DeleteMilestoneNotFound describes a response with status code 404, with default header values.

Resource does not exist
*/
type DeleteMilestoneNotFound struct {
}

// IsSuccess returns true when this delete milestone not found response has a 2xx status code
func (o *DeleteMilestoneNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete milestone not found response has a 3xx status code
func (o *DeleteMilestoneNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete milestone not found response has a 4xx status code
func (o *DeleteMilestoneNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete milestone not found response has a 5xx status code
func (o *DeleteMilestoneNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this delete milestone not found response a status code equal to that given
func (o *DeleteMilestoneNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the delete milestone not found response
func (o *DeleteMilestoneNotFound) Code() int {
	return 404
}

func (o *DeleteMilestoneNotFound) Error() string {
	return fmt.Sprintf("[DELETE /api/v3/milestones/{milestone-public-id}][%d] deleteMilestoneNotFound", 404)
}

func (o *DeleteMilestoneNotFound) String() string {
	return fmt.Sprintf("[DELETE /api/v3/milestones/{milestone-public-id}][%d] deleteMilestoneNotFound", 404)
}

func (o *DeleteMilestoneNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteMilestoneUnprocessableEntity creates a DeleteMilestoneUnprocessableEntity with default headers values
func NewDeleteMilestoneUnprocessableEntity() *DeleteMilestoneUnprocessableEntity {
	return &DeleteMilestoneUnprocessableEntity{}
}

/*
DeleteMilestoneUnprocessableEntity describes a response with status code 422, with default header values.

Unprocessable
*/
type DeleteMilestoneUnprocessableEntity struct {
}

// IsSuccess returns true when this delete milestone unprocessable entity response has a 2xx status code
func (o *DeleteMilestoneUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete milestone unprocessable entity response has a 3xx status code
func (o *DeleteMilestoneUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete milestone unprocessable entity response has a 4xx status code
func (o *DeleteMilestoneUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete milestone unprocessable entity response has a 5xx status code
func (o *DeleteMilestoneUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this delete milestone unprocessable entity response a status code equal to that given
func (o *DeleteMilestoneUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

// Code gets the status code for the delete milestone unprocessable entity response
func (o *DeleteMilestoneUnprocessableEntity) Code() int {
	return 422
}

func (o *DeleteMilestoneUnprocessableEntity) Error() string {
	return fmt.Sprintf("[DELETE /api/v3/milestones/{milestone-public-id}][%d] deleteMilestoneUnprocessableEntity", 422)
}

func (o *DeleteMilestoneUnprocessableEntity) String() string {
	return fmt.Sprintf("[DELETE /api/v3/milestones/{milestone-public-id}][%d] deleteMilestoneUnprocessableEntity", 422)
}

func (o *DeleteMilestoneUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
