// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteLinkedFileReader is a Reader for the DeleteLinkedFile structure.
type DeleteLinkedFileReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteLinkedFileReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteLinkedFileNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteLinkedFileBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteLinkedFileNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewDeleteLinkedFileUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteLinkedFileNoContent creates a DeleteLinkedFileNoContent with default headers values
func NewDeleteLinkedFileNoContent() *DeleteLinkedFileNoContent {
	return &DeleteLinkedFileNoContent{}
}

/*
DeleteLinkedFileNoContent describes a response with status code 204, with default header values.

No Content
*/
type DeleteLinkedFileNoContent struct {
}

// IsSuccess returns true when this delete linked file no content response has a 2xx status code
func (o *DeleteLinkedFileNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete linked file no content response has a 3xx status code
func (o *DeleteLinkedFileNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete linked file no content response has a 4xx status code
func (o *DeleteLinkedFileNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete linked file no content response has a 5xx status code
func (o *DeleteLinkedFileNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this delete linked file no content response a status code equal to that given
func (o *DeleteLinkedFileNoContent) IsCode(code int) bool {
	return code == 204
}

func (o *DeleteLinkedFileNoContent) Error() string {
	return fmt.Sprintf("[DELETE /api/v3/linked-files/{linked-file-public-id}][%d] deleteLinkedFileNoContent ", 204)
}

func (o *DeleteLinkedFileNoContent) String() string {
	return fmt.Sprintf("[DELETE /api/v3/linked-files/{linked-file-public-id}][%d] deleteLinkedFileNoContent ", 204)
}

func (o *DeleteLinkedFileNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteLinkedFileBadRequest creates a DeleteLinkedFileBadRequest with default headers values
func NewDeleteLinkedFileBadRequest() *DeleteLinkedFileBadRequest {
	return &DeleteLinkedFileBadRequest{}
}

/*
DeleteLinkedFileBadRequest describes a response with status code 400, with default header values.

Schema mismatch
*/
type DeleteLinkedFileBadRequest struct {
}

// IsSuccess returns true when this delete linked file bad request response has a 2xx status code
func (o *DeleteLinkedFileBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete linked file bad request response has a 3xx status code
func (o *DeleteLinkedFileBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete linked file bad request response has a 4xx status code
func (o *DeleteLinkedFileBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete linked file bad request response has a 5xx status code
func (o *DeleteLinkedFileBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this delete linked file bad request response a status code equal to that given
func (o *DeleteLinkedFileBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *DeleteLinkedFileBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /api/v3/linked-files/{linked-file-public-id}][%d] deleteLinkedFileBadRequest ", 400)
}

func (o *DeleteLinkedFileBadRequest) String() string {
	return fmt.Sprintf("[DELETE /api/v3/linked-files/{linked-file-public-id}][%d] deleteLinkedFileBadRequest ", 400)
}

func (o *DeleteLinkedFileBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteLinkedFileNotFound creates a DeleteLinkedFileNotFound with default headers values
func NewDeleteLinkedFileNotFound() *DeleteLinkedFileNotFound {
	return &DeleteLinkedFileNotFound{}
}

/*
DeleteLinkedFileNotFound describes a response with status code 404, with default header values.

Resource does not exist
*/
type DeleteLinkedFileNotFound struct {
}

// IsSuccess returns true when this delete linked file not found response has a 2xx status code
func (o *DeleteLinkedFileNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete linked file not found response has a 3xx status code
func (o *DeleteLinkedFileNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete linked file not found response has a 4xx status code
func (o *DeleteLinkedFileNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete linked file not found response has a 5xx status code
func (o *DeleteLinkedFileNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this delete linked file not found response a status code equal to that given
func (o *DeleteLinkedFileNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *DeleteLinkedFileNotFound) Error() string {
	return fmt.Sprintf("[DELETE /api/v3/linked-files/{linked-file-public-id}][%d] deleteLinkedFileNotFound ", 404)
}

func (o *DeleteLinkedFileNotFound) String() string {
	return fmt.Sprintf("[DELETE /api/v3/linked-files/{linked-file-public-id}][%d] deleteLinkedFileNotFound ", 404)
}

func (o *DeleteLinkedFileNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteLinkedFileUnprocessableEntity creates a DeleteLinkedFileUnprocessableEntity with default headers values
func NewDeleteLinkedFileUnprocessableEntity() *DeleteLinkedFileUnprocessableEntity {
	return &DeleteLinkedFileUnprocessableEntity{}
}

/*
DeleteLinkedFileUnprocessableEntity describes a response with status code 422, with default header values.

Unprocessable
*/
type DeleteLinkedFileUnprocessableEntity struct {
}

// IsSuccess returns true when this delete linked file unprocessable entity response has a 2xx status code
func (o *DeleteLinkedFileUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete linked file unprocessable entity response has a 3xx status code
func (o *DeleteLinkedFileUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete linked file unprocessable entity response has a 4xx status code
func (o *DeleteLinkedFileUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete linked file unprocessable entity response has a 5xx status code
func (o *DeleteLinkedFileUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this delete linked file unprocessable entity response a status code equal to that given
func (o *DeleteLinkedFileUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

func (o *DeleteLinkedFileUnprocessableEntity) Error() string {
	return fmt.Sprintf("[DELETE /api/v3/linked-files/{linked-file-public-id}][%d] deleteLinkedFileUnprocessableEntity ", 422)
}

func (o *DeleteLinkedFileUnprocessableEntity) String() string {
	return fmt.Sprintf("[DELETE /api/v3/linked-files/{linked-file-public-id}][%d] deleteLinkedFileUnprocessableEntity ", 422)
}

func (o *DeleteLinkedFileUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
