// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// EnableStoryTemplatesReader is a Reader for the EnableStoryTemplates structure.
type EnableStoryTemplatesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EnableStoryTemplatesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewEnableStoryTemplatesNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewEnableStoryTemplatesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewEnableStoryTemplatesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewEnableStoryTemplatesUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PUT /api/v3/entity-templates/enable] enableStoryTemplates", response, response.Code())
	}
}

// NewEnableStoryTemplatesNoContent creates a EnableStoryTemplatesNoContent with default headers values
func NewEnableStoryTemplatesNoContent() *EnableStoryTemplatesNoContent {
	return &EnableStoryTemplatesNoContent{}
}

/*
EnableStoryTemplatesNoContent describes a response with status code 204, with default header values.

No Content
*/
type EnableStoryTemplatesNoContent struct {
}

// IsSuccess returns true when this enable story templates no content response has a 2xx status code
func (o *EnableStoryTemplatesNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this enable story templates no content response has a 3xx status code
func (o *EnableStoryTemplatesNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this enable story templates no content response has a 4xx status code
func (o *EnableStoryTemplatesNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this enable story templates no content response has a 5xx status code
func (o *EnableStoryTemplatesNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this enable story templates no content response a status code equal to that given
func (o *EnableStoryTemplatesNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the enable story templates no content response
func (o *EnableStoryTemplatesNoContent) Code() int {
	return 204
}

func (o *EnableStoryTemplatesNoContent) Error() string {
	return fmt.Sprintf("[PUT /api/v3/entity-templates/enable][%d] enableStoryTemplatesNoContent", 204)
}

func (o *EnableStoryTemplatesNoContent) String() string {
	return fmt.Sprintf("[PUT /api/v3/entity-templates/enable][%d] enableStoryTemplatesNoContent", 204)
}

func (o *EnableStoryTemplatesNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewEnableStoryTemplatesBadRequest creates a EnableStoryTemplatesBadRequest with default headers values
func NewEnableStoryTemplatesBadRequest() *EnableStoryTemplatesBadRequest {
	return &EnableStoryTemplatesBadRequest{}
}

/*
EnableStoryTemplatesBadRequest describes a response with status code 400, with default header values.

Schema mismatch
*/
type EnableStoryTemplatesBadRequest struct {
}

// IsSuccess returns true when this enable story templates bad request response has a 2xx status code
func (o *EnableStoryTemplatesBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this enable story templates bad request response has a 3xx status code
func (o *EnableStoryTemplatesBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this enable story templates bad request response has a 4xx status code
func (o *EnableStoryTemplatesBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this enable story templates bad request response has a 5xx status code
func (o *EnableStoryTemplatesBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this enable story templates bad request response a status code equal to that given
func (o *EnableStoryTemplatesBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the enable story templates bad request response
func (o *EnableStoryTemplatesBadRequest) Code() int {
	return 400
}

func (o *EnableStoryTemplatesBadRequest) Error() string {
	return fmt.Sprintf("[PUT /api/v3/entity-templates/enable][%d] enableStoryTemplatesBadRequest", 400)
}

func (o *EnableStoryTemplatesBadRequest) String() string {
	return fmt.Sprintf("[PUT /api/v3/entity-templates/enable][%d] enableStoryTemplatesBadRequest", 400)
}

func (o *EnableStoryTemplatesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewEnableStoryTemplatesNotFound creates a EnableStoryTemplatesNotFound with default headers values
func NewEnableStoryTemplatesNotFound() *EnableStoryTemplatesNotFound {
	return &EnableStoryTemplatesNotFound{}
}

/*
EnableStoryTemplatesNotFound describes a response with status code 404, with default header values.

Resource does not exist
*/
type EnableStoryTemplatesNotFound struct {
}

// IsSuccess returns true when this enable story templates not found response has a 2xx status code
func (o *EnableStoryTemplatesNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this enable story templates not found response has a 3xx status code
func (o *EnableStoryTemplatesNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this enable story templates not found response has a 4xx status code
func (o *EnableStoryTemplatesNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this enable story templates not found response has a 5xx status code
func (o *EnableStoryTemplatesNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this enable story templates not found response a status code equal to that given
func (o *EnableStoryTemplatesNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the enable story templates not found response
func (o *EnableStoryTemplatesNotFound) Code() int {
	return 404
}

func (o *EnableStoryTemplatesNotFound) Error() string {
	return fmt.Sprintf("[PUT /api/v3/entity-templates/enable][%d] enableStoryTemplatesNotFound", 404)
}

func (o *EnableStoryTemplatesNotFound) String() string {
	return fmt.Sprintf("[PUT /api/v3/entity-templates/enable][%d] enableStoryTemplatesNotFound", 404)
}

func (o *EnableStoryTemplatesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewEnableStoryTemplatesUnprocessableEntity creates a EnableStoryTemplatesUnprocessableEntity with default headers values
func NewEnableStoryTemplatesUnprocessableEntity() *EnableStoryTemplatesUnprocessableEntity {
	return &EnableStoryTemplatesUnprocessableEntity{}
}

/*
EnableStoryTemplatesUnprocessableEntity describes a response with status code 422, with default header values.

Unprocessable
*/
type EnableStoryTemplatesUnprocessableEntity struct {
}

// IsSuccess returns true when this enable story templates unprocessable entity response has a 2xx status code
func (o *EnableStoryTemplatesUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this enable story templates unprocessable entity response has a 3xx status code
func (o *EnableStoryTemplatesUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this enable story templates unprocessable entity response has a 4xx status code
func (o *EnableStoryTemplatesUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this enable story templates unprocessable entity response has a 5xx status code
func (o *EnableStoryTemplatesUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this enable story templates unprocessable entity response a status code equal to that given
func (o *EnableStoryTemplatesUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

// Code gets the status code for the enable story templates unprocessable entity response
func (o *EnableStoryTemplatesUnprocessableEntity) Code() int {
	return 422
}

func (o *EnableStoryTemplatesUnprocessableEntity) Error() string {
	return fmt.Sprintf("[PUT /api/v3/entity-templates/enable][%d] enableStoryTemplatesUnprocessableEntity", 422)
}

func (o *EnableStoryTemplatesUnprocessableEntity) String() string {
	return fmt.Sprintf("[PUT /api/v3/entity-templates/enable][%d] enableStoryTemplatesUnprocessableEntity", 422)
}

func (o *EnableStoryTemplatesUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
