// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/FindHotel/shortcut-go/models"
)

// GetEntityTemplateReader is a Reader for the GetEntityTemplate structure.
type GetEntityTemplateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetEntityTemplateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetEntityTemplateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetEntityTemplateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetEntityTemplateNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewGetEntityTemplateUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/v3/entity-templates/{entity-template-public-id}] getEntityTemplate", response, response.Code())
	}
}

// NewGetEntityTemplateOK creates a GetEntityTemplateOK with default headers values
func NewGetEntityTemplateOK() *GetEntityTemplateOK {
	return &GetEntityTemplateOK{}
}

/*
GetEntityTemplateOK describes a response with status code 200, with default header values.

Resource
*/
type GetEntityTemplateOK struct {
	Payload *models.EntityTemplate
}

// IsSuccess returns true when this get entity template o k response has a 2xx status code
func (o *GetEntityTemplateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get entity template o k response has a 3xx status code
func (o *GetEntityTemplateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get entity template o k response has a 4xx status code
func (o *GetEntityTemplateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get entity template o k response has a 5xx status code
func (o *GetEntityTemplateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get entity template o k response a status code equal to that given
func (o *GetEntityTemplateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get entity template o k response
func (o *GetEntityTemplateOK) Code() int {
	return 200
}

func (o *GetEntityTemplateOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v3/entity-templates/{entity-template-public-id}][%d] getEntityTemplateOK %s", 200, payload)
}

func (o *GetEntityTemplateOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v3/entity-templates/{entity-template-public-id}][%d] getEntityTemplateOK %s", 200, payload)
}

func (o *GetEntityTemplateOK) GetPayload() *models.EntityTemplate {
	return o.Payload
}

func (o *GetEntityTemplateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EntityTemplate)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetEntityTemplateBadRequest creates a GetEntityTemplateBadRequest with default headers values
func NewGetEntityTemplateBadRequest() *GetEntityTemplateBadRequest {
	return &GetEntityTemplateBadRequest{}
}

/*
GetEntityTemplateBadRequest describes a response with status code 400, with default header values.

Schema mismatch
*/
type GetEntityTemplateBadRequest struct {
}

// IsSuccess returns true when this get entity template bad request response has a 2xx status code
func (o *GetEntityTemplateBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get entity template bad request response has a 3xx status code
func (o *GetEntityTemplateBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get entity template bad request response has a 4xx status code
func (o *GetEntityTemplateBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get entity template bad request response has a 5xx status code
func (o *GetEntityTemplateBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get entity template bad request response a status code equal to that given
func (o *GetEntityTemplateBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get entity template bad request response
func (o *GetEntityTemplateBadRequest) Code() int {
	return 400
}

func (o *GetEntityTemplateBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/v3/entity-templates/{entity-template-public-id}][%d] getEntityTemplateBadRequest", 400)
}

func (o *GetEntityTemplateBadRequest) String() string {
	return fmt.Sprintf("[GET /api/v3/entity-templates/{entity-template-public-id}][%d] getEntityTemplateBadRequest", 400)
}

func (o *GetEntityTemplateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetEntityTemplateNotFound creates a GetEntityTemplateNotFound with default headers values
func NewGetEntityTemplateNotFound() *GetEntityTemplateNotFound {
	return &GetEntityTemplateNotFound{}
}

/*
GetEntityTemplateNotFound describes a response with status code 404, with default header values.

Resource does not exist
*/
type GetEntityTemplateNotFound struct {
}

// IsSuccess returns true when this get entity template not found response has a 2xx status code
func (o *GetEntityTemplateNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get entity template not found response has a 3xx status code
func (o *GetEntityTemplateNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get entity template not found response has a 4xx status code
func (o *GetEntityTemplateNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get entity template not found response has a 5xx status code
func (o *GetEntityTemplateNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get entity template not found response a status code equal to that given
func (o *GetEntityTemplateNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get entity template not found response
func (o *GetEntityTemplateNotFound) Code() int {
	return 404
}

func (o *GetEntityTemplateNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v3/entity-templates/{entity-template-public-id}][%d] getEntityTemplateNotFound", 404)
}

func (o *GetEntityTemplateNotFound) String() string {
	return fmt.Sprintf("[GET /api/v3/entity-templates/{entity-template-public-id}][%d] getEntityTemplateNotFound", 404)
}

func (o *GetEntityTemplateNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetEntityTemplateUnprocessableEntity creates a GetEntityTemplateUnprocessableEntity with default headers values
func NewGetEntityTemplateUnprocessableEntity() *GetEntityTemplateUnprocessableEntity {
	return &GetEntityTemplateUnprocessableEntity{}
}

/*
GetEntityTemplateUnprocessableEntity describes a response with status code 422, with default header values.

Unprocessable
*/
type GetEntityTemplateUnprocessableEntity struct {
}

// IsSuccess returns true when this get entity template unprocessable entity response has a 2xx status code
func (o *GetEntityTemplateUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get entity template unprocessable entity response has a 3xx status code
func (o *GetEntityTemplateUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get entity template unprocessable entity response has a 4xx status code
func (o *GetEntityTemplateUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this get entity template unprocessable entity response has a 5xx status code
func (o *GetEntityTemplateUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this get entity template unprocessable entity response a status code equal to that given
func (o *GetEntityTemplateUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

// Code gets the status code for the get entity template unprocessable entity response
func (o *GetEntityTemplateUnprocessableEntity) Code() int {
	return 422
}

func (o *GetEntityTemplateUnprocessableEntity) Error() string {
	return fmt.Sprintf("[GET /api/v3/entity-templates/{entity-template-public-id}][%d] getEntityTemplateUnprocessableEntity", 422)
}

func (o *GetEntityTemplateUnprocessableEntity) String() string {
	return fmt.Sprintf("[GET /api/v3/entity-templates/{entity-template-public-id}][%d] getEntityTemplateUnprocessableEntity", 422)
}

func (o *GetEntityTemplateUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
