// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/FindHotel/shortcut-go/models"
)

// GetEpicReader is a Reader for the GetEpic structure.
type GetEpicReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetEpicReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetEpicOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetEpicBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetEpicNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewGetEpicUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/v3/epics/{epic-public-id}] getEpic", response, response.Code())
	}
}

// NewGetEpicOK creates a GetEpicOK with default headers values
func NewGetEpicOK() *GetEpicOK {
	return &GetEpicOK{}
}

/*
GetEpicOK describes a response with status code 200, with default header values.

Resource
*/
type GetEpicOK struct {
	Payload *models.Epic
}

// IsSuccess returns true when this get epic o k response has a 2xx status code
func (o *GetEpicOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get epic o k response has a 3xx status code
func (o *GetEpicOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get epic o k response has a 4xx status code
func (o *GetEpicOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get epic o k response has a 5xx status code
func (o *GetEpicOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get epic o k response a status code equal to that given
func (o *GetEpicOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get epic o k response
func (o *GetEpicOK) Code() int {
	return 200
}

func (o *GetEpicOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v3/epics/{epic-public-id}][%d] getEpicOK %s", 200, payload)
}

func (o *GetEpicOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v3/epics/{epic-public-id}][%d] getEpicOK %s", 200, payload)
}

func (o *GetEpicOK) GetPayload() *models.Epic {
	return o.Payload
}

func (o *GetEpicOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Epic)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetEpicBadRequest creates a GetEpicBadRequest with default headers values
func NewGetEpicBadRequest() *GetEpicBadRequest {
	return &GetEpicBadRequest{}
}

/*
GetEpicBadRequest describes a response with status code 400, with default header values.

Schema mismatch
*/
type GetEpicBadRequest struct {
}

// IsSuccess returns true when this get epic bad request response has a 2xx status code
func (o *GetEpicBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get epic bad request response has a 3xx status code
func (o *GetEpicBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get epic bad request response has a 4xx status code
func (o *GetEpicBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get epic bad request response has a 5xx status code
func (o *GetEpicBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get epic bad request response a status code equal to that given
func (o *GetEpicBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get epic bad request response
func (o *GetEpicBadRequest) Code() int {
	return 400
}

func (o *GetEpicBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/v3/epics/{epic-public-id}][%d] getEpicBadRequest", 400)
}

func (o *GetEpicBadRequest) String() string {
	return fmt.Sprintf("[GET /api/v3/epics/{epic-public-id}][%d] getEpicBadRequest", 400)
}

func (o *GetEpicBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetEpicNotFound creates a GetEpicNotFound with default headers values
func NewGetEpicNotFound() *GetEpicNotFound {
	return &GetEpicNotFound{}
}

/*
GetEpicNotFound describes a response with status code 404, with default header values.

Resource does not exist
*/
type GetEpicNotFound struct {
}

// IsSuccess returns true when this get epic not found response has a 2xx status code
func (o *GetEpicNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get epic not found response has a 3xx status code
func (o *GetEpicNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get epic not found response has a 4xx status code
func (o *GetEpicNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get epic not found response has a 5xx status code
func (o *GetEpicNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get epic not found response a status code equal to that given
func (o *GetEpicNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get epic not found response
func (o *GetEpicNotFound) Code() int {
	return 404
}

func (o *GetEpicNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v3/epics/{epic-public-id}][%d] getEpicNotFound", 404)
}

func (o *GetEpicNotFound) String() string {
	return fmt.Sprintf("[GET /api/v3/epics/{epic-public-id}][%d] getEpicNotFound", 404)
}

func (o *GetEpicNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetEpicUnprocessableEntity creates a GetEpicUnprocessableEntity with default headers values
func NewGetEpicUnprocessableEntity() *GetEpicUnprocessableEntity {
	return &GetEpicUnprocessableEntity{}
}

/*
GetEpicUnprocessableEntity describes a response with status code 422, with default header values.

Unprocessable
*/
type GetEpicUnprocessableEntity struct {
}

// IsSuccess returns true when this get epic unprocessable entity response has a 2xx status code
func (o *GetEpicUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get epic unprocessable entity response has a 3xx status code
func (o *GetEpicUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get epic unprocessable entity response has a 4xx status code
func (o *GetEpicUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this get epic unprocessable entity response has a 5xx status code
func (o *GetEpicUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this get epic unprocessable entity response a status code equal to that given
func (o *GetEpicUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

// Code gets the status code for the get epic unprocessable entity response
func (o *GetEpicUnprocessableEntity) Code() int {
	return 422
}

func (o *GetEpicUnprocessableEntity) Error() string {
	return fmt.Sprintf("[GET /api/v3/epics/{epic-public-id}][%d] getEpicUnprocessableEntity", 422)
}

func (o *GetEpicUnprocessableEntity) String() string {
	return fmt.Sprintf("[GET /api/v3/epics/{epic-public-id}][%d] getEpicUnprocessableEntity", 422)
}

func (o *GetEpicUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
