// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/FindHotel/shortcut-go/models"
)

// GetLinkedFileReader is a Reader for the GetLinkedFile structure.
type GetLinkedFileReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetLinkedFileReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetLinkedFileOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetLinkedFileBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetLinkedFileNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewGetLinkedFileUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/v3/linked-files/{linked-file-public-id}] getLinkedFile", response, response.Code())
	}
}

// NewGetLinkedFileOK creates a GetLinkedFileOK with default headers values
func NewGetLinkedFileOK() *GetLinkedFileOK {
	return &GetLinkedFileOK{}
}

/*
GetLinkedFileOK describes a response with status code 200, with default header values.

Resource
*/
type GetLinkedFileOK struct {
	Payload *models.LinkedFile
}

// IsSuccess returns true when this get linked file o k response has a 2xx status code
func (o *GetLinkedFileOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get linked file o k response has a 3xx status code
func (o *GetLinkedFileOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get linked file o k response has a 4xx status code
func (o *GetLinkedFileOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get linked file o k response has a 5xx status code
func (o *GetLinkedFileOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get linked file o k response a status code equal to that given
func (o *GetLinkedFileOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get linked file o k response
func (o *GetLinkedFileOK) Code() int {
	return 200
}

func (o *GetLinkedFileOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v3/linked-files/{linked-file-public-id}][%d] getLinkedFileOK %s", 200, payload)
}

func (o *GetLinkedFileOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v3/linked-files/{linked-file-public-id}][%d] getLinkedFileOK %s", 200, payload)
}

func (o *GetLinkedFileOK) GetPayload() *models.LinkedFile {
	return o.Payload
}

func (o *GetLinkedFileOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.LinkedFile)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetLinkedFileBadRequest creates a GetLinkedFileBadRequest with default headers values
func NewGetLinkedFileBadRequest() *GetLinkedFileBadRequest {
	return &GetLinkedFileBadRequest{}
}

/*
GetLinkedFileBadRequest describes a response with status code 400, with default header values.

Schema mismatch
*/
type GetLinkedFileBadRequest struct {
}

// IsSuccess returns true when this get linked file bad request response has a 2xx status code
func (o *GetLinkedFileBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get linked file bad request response has a 3xx status code
func (o *GetLinkedFileBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get linked file bad request response has a 4xx status code
func (o *GetLinkedFileBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get linked file bad request response has a 5xx status code
func (o *GetLinkedFileBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get linked file bad request response a status code equal to that given
func (o *GetLinkedFileBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get linked file bad request response
func (o *GetLinkedFileBadRequest) Code() int {
	return 400
}

func (o *GetLinkedFileBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/v3/linked-files/{linked-file-public-id}][%d] getLinkedFileBadRequest", 400)
}

func (o *GetLinkedFileBadRequest) String() string {
	return fmt.Sprintf("[GET /api/v3/linked-files/{linked-file-public-id}][%d] getLinkedFileBadRequest", 400)
}

func (o *GetLinkedFileBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetLinkedFileNotFound creates a GetLinkedFileNotFound with default headers values
func NewGetLinkedFileNotFound() *GetLinkedFileNotFound {
	return &GetLinkedFileNotFound{}
}

/*
GetLinkedFileNotFound describes a response with status code 404, with default header values.

Resource does not exist
*/
type GetLinkedFileNotFound struct {
}

// IsSuccess returns true when this get linked file not found response has a 2xx status code
func (o *GetLinkedFileNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get linked file not found response has a 3xx status code
func (o *GetLinkedFileNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get linked file not found response has a 4xx status code
func (o *GetLinkedFileNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get linked file not found response has a 5xx status code
func (o *GetLinkedFileNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get linked file not found response a status code equal to that given
func (o *GetLinkedFileNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get linked file not found response
func (o *GetLinkedFileNotFound) Code() int {
	return 404
}

func (o *GetLinkedFileNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v3/linked-files/{linked-file-public-id}][%d] getLinkedFileNotFound", 404)
}

func (o *GetLinkedFileNotFound) String() string {
	return fmt.Sprintf("[GET /api/v3/linked-files/{linked-file-public-id}][%d] getLinkedFileNotFound", 404)
}

func (o *GetLinkedFileNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetLinkedFileUnprocessableEntity creates a GetLinkedFileUnprocessableEntity with default headers values
func NewGetLinkedFileUnprocessableEntity() *GetLinkedFileUnprocessableEntity {
	return &GetLinkedFileUnprocessableEntity{}
}

/*
GetLinkedFileUnprocessableEntity describes a response with status code 422, with default header values.

Unprocessable
*/
type GetLinkedFileUnprocessableEntity struct {
}

// IsSuccess returns true when this get linked file unprocessable entity response has a 2xx status code
func (o *GetLinkedFileUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get linked file unprocessable entity response has a 3xx status code
func (o *GetLinkedFileUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get linked file unprocessable entity response has a 4xx status code
func (o *GetLinkedFileUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this get linked file unprocessable entity response has a 5xx status code
func (o *GetLinkedFileUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this get linked file unprocessable entity response a status code equal to that given
func (o *GetLinkedFileUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

// Code gets the status code for the get linked file unprocessable entity response
func (o *GetLinkedFileUnprocessableEntity) Code() int {
	return 422
}

func (o *GetLinkedFileUnprocessableEntity) Error() string {
	return fmt.Sprintf("[GET /api/v3/linked-files/{linked-file-public-id}][%d] getLinkedFileUnprocessableEntity", 422)
}

func (o *GetLinkedFileUnprocessableEntity) String() string {
	return fmt.Sprintf("[GET /api/v3/linked-files/{linked-file-public-id}][%d] getLinkedFileUnprocessableEntity", 422)
}

func (o *GetLinkedFileUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
