// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/FindHotel/shortcut-go/models"
)

// ListIterationStoriesReader is a Reader for the ListIterationStories structure.
type ListIterationStoriesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListIterationStoriesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListIterationStoriesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewListIterationStoriesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewListIterationStoriesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewListIterationStoriesUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListIterationStoriesOK creates a ListIterationStoriesOK with default headers values
func NewListIterationStoriesOK() *ListIterationStoriesOK {
	return &ListIterationStoriesOK{}
}

/*
ListIterationStoriesOK describes a response with status code 200, with default header values.

Resource
*/
type ListIterationStoriesOK struct {
	Payload []*models.StorySlim
}

// IsSuccess returns true when this list iteration stories o k response has a 2xx status code
func (o *ListIterationStoriesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list iteration stories o k response has a 3xx status code
func (o *ListIterationStoriesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list iteration stories o k response has a 4xx status code
func (o *ListIterationStoriesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list iteration stories o k response has a 5xx status code
func (o *ListIterationStoriesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list iteration stories o k response a status code equal to that given
func (o *ListIterationStoriesOK) IsCode(code int) bool {
	return code == 200
}

func (o *ListIterationStoriesOK) Error() string {
	return fmt.Sprintf("[GET /api/v3/iterations/{iteration-public-id}/stories][%d] listIterationStoriesOK  %+v", 200, o.Payload)
}

func (o *ListIterationStoriesOK) String() string {
	return fmt.Sprintf("[GET /api/v3/iterations/{iteration-public-id}/stories][%d] listIterationStoriesOK  %+v", 200, o.Payload)
}

func (o *ListIterationStoriesOK) GetPayload() []*models.StorySlim {
	return o.Payload
}

func (o *ListIterationStoriesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListIterationStoriesBadRequest creates a ListIterationStoriesBadRequest with default headers values
func NewListIterationStoriesBadRequest() *ListIterationStoriesBadRequest {
	return &ListIterationStoriesBadRequest{}
}

/*
ListIterationStoriesBadRequest describes a response with status code 400, with default header values.

Schema mismatch
*/
type ListIterationStoriesBadRequest struct {
}

// IsSuccess returns true when this list iteration stories bad request response has a 2xx status code
func (o *ListIterationStoriesBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list iteration stories bad request response has a 3xx status code
func (o *ListIterationStoriesBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list iteration stories bad request response has a 4xx status code
func (o *ListIterationStoriesBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this list iteration stories bad request response has a 5xx status code
func (o *ListIterationStoriesBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this list iteration stories bad request response a status code equal to that given
func (o *ListIterationStoriesBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *ListIterationStoriesBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/v3/iterations/{iteration-public-id}/stories][%d] listIterationStoriesBadRequest ", 400)
}

func (o *ListIterationStoriesBadRequest) String() string {
	return fmt.Sprintf("[GET /api/v3/iterations/{iteration-public-id}/stories][%d] listIterationStoriesBadRequest ", 400)
}

func (o *ListIterationStoriesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewListIterationStoriesNotFound creates a ListIterationStoriesNotFound with default headers values
func NewListIterationStoriesNotFound() *ListIterationStoriesNotFound {
	return &ListIterationStoriesNotFound{}
}

/*
ListIterationStoriesNotFound describes a response with status code 404, with default header values.

Resource does not exist
*/
type ListIterationStoriesNotFound struct {
}

// IsSuccess returns true when this list iteration stories not found response has a 2xx status code
func (o *ListIterationStoriesNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list iteration stories not found response has a 3xx status code
func (o *ListIterationStoriesNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list iteration stories not found response has a 4xx status code
func (o *ListIterationStoriesNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this list iteration stories not found response has a 5xx status code
func (o *ListIterationStoriesNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this list iteration stories not found response a status code equal to that given
func (o *ListIterationStoriesNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *ListIterationStoriesNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v3/iterations/{iteration-public-id}/stories][%d] listIterationStoriesNotFound ", 404)
}

func (o *ListIterationStoriesNotFound) String() string {
	return fmt.Sprintf("[GET /api/v3/iterations/{iteration-public-id}/stories][%d] listIterationStoriesNotFound ", 404)
}

func (o *ListIterationStoriesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewListIterationStoriesUnprocessableEntity creates a ListIterationStoriesUnprocessableEntity with default headers values
func NewListIterationStoriesUnprocessableEntity() *ListIterationStoriesUnprocessableEntity {
	return &ListIterationStoriesUnprocessableEntity{}
}

/*
ListIterationStoriesUnprocessableEntity describes a response with status code 422, with default header values.

Unprocessable
*/
type ListIterationStoriesUnprocessableEntity struct {
}

// IsSuccess returns true when this list iteration stories unprocessable entity response has a 2xx status code
func (o *ListIterationStoriesUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list iteration stories unprocessable entity response has a 3xx status code
func (o *ListIterationStoriesUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list iteration stories unprocessable entity response has a 4xx status code
func (o *ListIterationStoriesUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this list iteration stories unprocessable entity response has a 5xx status code
func (o *ListIterationStoriesUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this list iteration stories unprocessable entity response a status code equal to that given
func (o *ListIterationStoriesUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

func (o *ListIterationStoriesUnprocessableEntity) Error() string {
	return fmt.Sprintf("[GET /api/v3/iterations/{iteration-public-id}/stories][%d] listIterationStoriesUnprocessableEntity ", 422)
}

func (o *ListIterationStoriesUnprocessableEntity) String() string {
	return fmt.Sprintf("[GET /api/v3/iterations/{iteration-public-id}/stories][%d] listIterationStoriesUnprocessableEntity ", 422)
}

func (o *ListIterationStoriesUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
