// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/FindHotel/shortcut-go/models"
)

// ListLabelEpicsReader is a Reader for the ListLabelEpics structure.
type ListLabelEpicsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListLabelEpicsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListLabelEpicsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewListLabelEpicsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewListLabelEpicsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewListLabelEpicsUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/v3/labels/{label-public-id}/epics] listLabelEpics", response, response.Code())
	}
}

// NewListLabelEpicsOK creates a ListLabelEpicsOK with default headers values
func NewListLabelEpicsOK() *ListLabelEpicsOK {
	return &ListLabelEpicsOK{}
}

/*
ListLabelEpicsOK describes a response with status code 200, with default header values.

Resource
*/
type ListLabelEpicsOK struct {
	Payload []*models.EpicSlim
}

// IsSuccess returns true when this list label epics o k response has a 2xx status code
func (o *ListLabelEpicsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list label epics o k response has a 3xx status code
func (o *ListLabelEpicsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list label epics o k response has a 4xx status code
func (o *ListLabelEpicsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list label epics o k response has a 5xx status code
func (o *ListLabelEpicsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list label epics o k response a status code equal to that given
func (o *ListLabelEpicsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list label epics o k response
func (o *ListLabelEpicsOK) Code() int {
	return 200
}

func (o *ListLabelEpicsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v3/labels/{label-public-id}/epics][%d] listLabelEpicsOK %s", 200, payload)
}

func (o *ListLabelEpicsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v3/labels/{label-public-id}/epics][%d] listLabelEpicsOK %s", 200, payload)
}

func (o *ListLabelEpicsOK) GetPayload() []*models.EpicSlim {
	return o.Payload
}

func (o *ListLabelEpicsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListLabelEpicsBadRequest creates a ListLabelEpicsBadRequest with default headers values
func NewListLabelEpicsBadRequest() *ListLabelEpicsBadRequest {
	return &ListLabelEpicsBadRequest{}
}

/*
ListLabelEpicsBadRequest describes a response with status code 400, with default header values.

Schema mismatch
*/
type ListLabelEpicsBadRequest struct {
}

// IsSuccess returns true when this list label epics bad request response has a 2xx status code
func (o *ListLabelEpicsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list label epics bad request response has a 3xx status code
func (o *ListLabelEpicsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list label epics bad request response has a 4xx status code
func (o *ListLabelEpicsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this list label epics bad request response has a 5xx status code
func (o *ListLabelEpicsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this list label epics bad request response a status code equal to that given
func (o *ListLabelEpicsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the list label epics bad request response
func (o *ListLabelEpicsBadRequest) Code() int {
	return 400
}

func (o *ListLabelEpicsBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/v3/labels/{label-public-id}/epics][%d] listLabelEpicsBadRequest", 400)
}

func (o *ListLabelEpicsBadRequest) String() string {
	return fmt.Sprintf("[GET /api/v3/labels/{label-public-id}/epics][%d] listLabelEpicsBadRequest", 400)
}

func (o *ListLabelEpicsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewListLabelEpicsNotFound creates a ListLabelEpicsNotFound with default headers values
func NewListLabelEpicsNotFound() *ListLabelEpicsNotFound {
	return &ListLabelEpicsNotFound{}
}

/*
ListLabelEpicsNotFound describes a response with status code 404, with default header values.

Resource does not exist
*/
type ListLabelEpicsNotFound struct {
}

// IsSuccess returns true when this list label epics not found response has a 2xx status code
func (o *ListLabelEpicsNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list label epics not found response has a 3xx status code
func (o *ListLabelEpicsNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list label epics not found response has a 4xx status code
func (o *ListLabelEpicsNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this list label epics not found response has a 5xx status code
func (o *ListLabelEpicsNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this list label epics not found response a status code equal to that given
func (o *ListLabelEpicsNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the list label epics not found response
func (o *ListLabelEpicsNotFound) Code() int {
	return 404
}

func (o *ListLabelEpicsNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v3/labels/{label-public-id}/epics][%d] listLabelEpicsNotFound", 404)
}

func (o *ListLabelEpicsNotFound) String() string {
	return fmt.Sprintf("[GET /api/v3/labels/{label-public-id}/epics][%d] listLabelEpicsNotFound", 404)
}

func (o *ListLabelEpicsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewListLabelEpicsUnprocessableEntity creates a ListLabelEpicsUnprocessableEntity with default headers values
func NewListLabelEpicsUnprocessableEntity() *ListLabelEpicsUnprocessableEntity {
	return &ListLabelEpicsUnprocessableEntity{}
}

/*
ListLabelEpicsUnprocessableEntity describes a response with status code 422, with default header values.

Unprocessable
*/
type ListLabelEpicsUnprocessableEntity struct {
}

// IsSuccess returns true when this list label epics unprocessable entity response has a 2xx status code
func (o *ListLabelEpicsUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list label epics unprocessable entity response has a 3xx status code
func (o *ListLabelEpicsUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list label epics unprocessable entity response has a 4xx status code
func (o *ListLabelEpicsUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this list label epics unprocessable entity response has a 5xx status code
func (o *ListLabelEpicsUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this list label epics unprocessable entity response a status code equal to that given
func (o *ListLabelEpicsUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

// Code gets the status code for the list label epics unprocessable entity response
func (o *ListLabelEpicsUnprocessableEntity) Code() int {
	return 422
}

func (o *ListLabelEpicsUnprocessableEntity) Error() string {
	return fmt.Sprintf("[GET /api/v3/labels/{label-public-id}/epics][%d] listLabelEpicsUnprocessableEntity", 422)
}

func (o *ListLabelEpicsUnprocessableEntity) String() string {
	return fmt.Sprintf("[GET /api/v3/labels/{label-public-id}/epics][%d] listLabelEpicsUnprocessableEntity", 422)
}

func (o *ListLabelEpicsUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
