// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/FindHotel/shortcut-go/models"
)

// ListCustomFieldsReader is a Reader for the ListCustomFields structure.
type ListCustomFieldsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListCustomFieldsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListCustomFieldsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewListCustomFieldsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewListCustomFieldsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewListCustomFieldsUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListCustomFieldsOK creates a ListCustomFieldsOK with default headers values
func NewListCustomFieldsOK() *ListCustomFieldsOK {
	return &ListCustomFieldsOK{}
}

/*
ListCustomFieldsOK describes a response with status code 200, with default header values.

Resource
*/
type ListCustomFieldsOK struct {
	Payload []*models.CustomField
}

// IsSuccess returns true when this list custom fields o k response has a 2xx status code
func (o *ListCustomFieldsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list custom fields o k response has a 3xx status code
func (o *ListCustomFieldsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list custom fields o k response has a 4xx status code
func (o *ListCustomFieldsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list custom fields o k response has a 5xx status code
func (o *ListCustomFieldsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list custom fields o k response a status code equal to that given
func (o *ListCustomFieldsOK) IsCode(code int) bool {
	return code == 200
}

func (o *ListCustomFieldsOK) Error() string {
	return fmt.Sprintf("[GET /api/v3/custom-fields][%d] listCustomFieldsOK  %+v", 200, o.Payload)
}

func (o *ListCustomFieldsOK) String() string {
	return fmt.Sprintf("[GET /api/v3/custom-fields][%d] listCustomFieldsOK  %+v", 200, o.Payload)
}

func (o *ListCustomFieldsOK) GetPayload() []*models.CustomField {
	return o.Payload
}

func (o *ListCustomFieldsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListCustomFieldsBadRequest creates a ListCustomFieldsBadRequest with default headers values
func NewListCustomFieldsBadRequest() *ListCustomFieldsBadRequest {
	return &ListCustomFieldsBadRequest{}
}

/*
ListCustomFieldsBadRequest describes a response with status code 400, with default header values.

Schema mismatch
*/
type ListCustomFieldsBadRequest struct {
}

// IsSuccess returns true when this list custom fields bad request response has a 2xx status code
func (o *ListCustomFieldsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list custom fields bad request response has a 3xx status code
func (o *ListCustomFieldsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list custom fields bad request response has a 4xx status code
func (o *ListCustomFieldsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this list custom fields bad request response has a 5xx status code
func (o *ListCustomFieldsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this list custom fields bad request response a status code equal to that given
func (o *ListCustomFieldsBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *ListCustomFieldsBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/v3/custom-fields][%d] listCustomFieldsBadRequest ", 400)
}

func (o *ListCustomFieldsBadRequest) String() string {
	return fmt.Sprintf("[GET /api/v3/custom-fields][%d] listCustomFieldsBadRequest ", 400)
}

func (o *ListCustomFieldsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewListCustomFieldsNotFound creates a ListCustomFieldsNotFound with default headers values
func NewListCustomFieldsNotFound() *ListCustomFieldsNotFound {
	return &ListCustomFieldsNotFound{}
}

/*
ListCustomFieldsNotFound describes a response with status code 404, with default header values.

Resource does not exist
*/
type ListCustomFieldsNotFound struct {
}

// IsSuccess returns true when this list custom fields not found response has a 2xx status code
func (o *ListCustomFieldsNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list custom fields not found response has a 3xx status code
func (o *ListCustomFieldsNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list custom fields not found response has a 4xx status code
func (o *ListCustomFieldsNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this list custom fields not found response has a 5xx status code
func (o *ListCustomFieldsNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this list custom fields not found response a status code equal to that given
func (o *ListCustomFieldsNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *ListCustomFieldsNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v3/custom-fields][%d] listCustomFieldsNotFound ", 404)
}

func (o *ListCustomFieldsNotFound) String() string {
	return fmt.Sprintf("[GET /api/v3/custom-fields][%d] listCustomFieldsNotFound ", 404)
}

func (o *ListCustomFieldsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewListCustomFieldsUnprocessableEntity creates a ListCustomFieldsUnprocessableEntity with default headers values
func NewListCustomFieldsUnprocessableEntity() *ListCustomFieldsUnprocessableEntity {
	return &ListCustomFieldsUnprocessableEntity{}
}

/*
ListCustomFieldsUnprocessableEntity describes a response with status code 422, with default header values.

Unprocessable
*/
type ListCustomFieldsUnprocessableEntity struct {
}

// IsSuccess returns true when this list custom fields unprocessable entity response has a 2xx status code
func (o *ListCustomFieldsUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list custom fields unprocessable entity response has a 3xx status code
func (o *ListCustomFieldsUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list custom fields unprocessable entity response has a 4xx status code
func (o *ListCustomFieldsUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this list custom fields unprocessable entity response has a 5xx status code
func (o *ListCustomFieldsUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this list custom fields unprocessable entity response a status code equal to that given
func (o *ListCustomFieldsUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

func (o *ListCustomFieldsUnprocessableEntity) Error() string {
	return fmt.Sprintf("[GET /api/v3/custom-fields][%d] listCustomFieldsUnprocessableEntity ", 422)
}

func (o *ListCustomFieldsUnprocessableEntity) String() string {
	return fmt.Sprintf("[GET /api/v3/custom-fields][%d] listCustomFieldsUnprocessableEntity ", 422)
}

func (o *ListCustomFieldsUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
