// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListCustomFieldsParams creates a new ListCustomFieldsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListCustomFieldsParams() *ListCustomFieldsParams {
	return &ListCustomFieldsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListCustomFieldsParamsWithTimeout creates a new ListCustomFieldsParams object
// with the ability to set a timeout on a request.
func NewListCustomFieldsParamsWithTimeout(timeout time.Duration) *ListCustomFieldsParams {
	return &ListCustomFieldsParams{
		timeout: timeout,
	}
}

// NewListCustomFieldsParamsWithContext creates a new ListCustomFieldsParams object
// with the ability to set a context for a request.
func NewListCustomFieldsParamsWithContext(ctx context.Context) *ListCustomFieldsParams {
	return &ListCustomFieldsParams{
		Context: ctx,
	}
}

// NewListCustomFieldsParamsWithHTTPClient creates a new ListCustomFieldsParams object
// with the ability to set a custom HTTPClient for a request.
func NewListCustomFieldsParamsWithHTTPClient(client *http.Client) *ListCustomFieldsParams {
	return &ListCustomFieldsParams{
		HTTPClient: client,
	}
}

/*
ListCustomFieldsParams contains all the parameters to send to the API endpoint

	for the list custom fields operation.

	Typically these are written to a http.Request.
*/
type ListCustomFieldsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list custom fields params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListCustomFieldsParams) WithDefaults() *ListCustomFieldsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list custom fields params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListCustomFieldsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list custom fields params
func (o *ListCustomFieldsParams) WithTimeout(timeout time.Duration) *ListCustomFieldsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list custom fields params
func (o *ListCustomFieldsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list custom fields params
func (o *ListCustomFieldsParams) WithContext(ctx context.Context) *ListCustomFieldsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list custom fields params
func (o *ListCustomFieldsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list custom fields params
func (o *ListCustomFieldsParams) WithHTTPClient(client *http.Client) *ListCustomFieldsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list custom fields params
func (o *ListCustomFieldsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ListCustomFieldsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
