// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/FindHotel/shortcut-go/models"
)

// ListMilestoneEpicsReader is a Reader for the ListMilestoneEpics structure.
type ListMilestoneEpicsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListMilestoneEpicsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListMilestoneEpicsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewListMilestoneEpicsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewListMilestoneEpicsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewListMilestoneEpicsUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/v3/milestones/{milestone-public-id}/epics] listMilestoneEpics", response, response.Code())
	}
}

// NewListMilestoneEpicsOK creates a ListMilestoneEpicsOK with default headers values
func NewListMilestoneEpicsOK() *ListMilestoneEpicsOK {
	return &ListMilestoneEpicsOK{}
}

/*
ListMilestoneEpicsOK describes a response with status code 200, with default header values.

Resource
*/
type ListMilestoneEpicsOK struct {
	Payload []*models.EpicSlim
}

// IsSuccess returns true when this list milestone epics o k response has a 2xx status code
func (o *ListMilestoneEpicsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list milestone epics o k response has a 3xx status code
func (o *ListMilestoneEpicsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list milestone epics o k response has a 4xx status code
func (o *ListMilestoneEpicsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list milestone epics o k response has a 5xx status code
func (o *ListMilestoneEpicsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list milestone epics o k response a status code equal to that given
func (o *ListMilestoneEpicsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list milestone epics o k response
func (o *ListMilestoneEpicsOK) Code() int {
	return 200
}

func (o *ListMilestoneEpicsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v3/milestones/{milestone-public-id}/epics][%d] listMilestoneEpicsOK %s", 200, payload)
}

func (o *ListMilestoneEpicsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v3/milestones/{milestone-public-id}/epics][%d] listMilestoneEpicsOK %s", 200, payload)
}

func (o *ListMilestoneEpicsOK) GetPayload() []*models.EpicSlim {
	return o.Payload
}

func (o *ListMilestoneEpicsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListMilestoneEpicsBadRequest creates a ListMilestoneEpicsBadRequest with default headers values
func NewListMilestoneEpicsBadRequest() *ListMilestoneEpicsBadRequest {
	return &ListMilestoneEpicsBadRequest{}
}

/*
ListMilestoneEpicsBadRequest describes a response with status code 400, with default header values.

Schema mismatch
*/
type ListMilestoneEpicsBadRequest struct {
}

// IsSuccess returns true when this list milestone epics bad request response has a 2xx status code
func (o *ListMilestoneEpicsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list milestone epics bad request response has a 3xx status code
func (o *ListMilestoneEpicsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list milestone epics bad request response has a 4xx status code
func (o *ListMilestoneEpicsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this list milestone epics bad request response has a 5xx status code
func (o *ListMilestoneEpicsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this list milestone epics bad request response a status code equal to that given
func (o *ListMilestoneEpicsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the list milestone epics bad request response
func (o *ListMilestoneEpicsBadRequest) Code() int {
	return 400
}

func (o *ListMilestoneEpicsBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/v3/milestones/{milestone-public-id}/epics][%d] listMilestoneEpicsBadRequest", 400)
}

func (o *ListMilestoneEpicsBadRequest) String() string {
	return fmt.Sprintf("[GET /api/v3/milestones/{milestone-public-id}/epics][%d] listMilestoneEpicsBadRequest", 400)
}

func (o *ListMilestoneEpicsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewListMilestoneEpicsNotFound creates a ListMilestoneEpicsNotFound with default headers values
func NewListMilestoneEpicsNotFound() *ListMilestoneEpicsNotFound {
	return &ListMilestoneEpicsNotFound{}
}

/*
ListMilestoneEpicsNotFound describes a response with status code 404, with default header values.

Resource does not exist
*/
type ListMilestoneEpicsNotFound struct {
}

// IsSuccess returns true when this list milestone epics not found response has a 2xx status code
func (o *ListMilestoneEpicsNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list milestone epics not found response has a 3xx status code
func (o *ListMilestoneEpicsNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list milestone epics not found response has a 4xx status code
func (o *ListMilestoneEpicsNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this list milestone epics not found response has a 5xx status code
func (o *ListMilestoneEpicsNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this list milestone epics not found response a status code equal to that given
func (o *ListMilestoneEpicsNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the list milestone epics not found response
func (o *ListMilestoneEpicsNotFound) Code() int {
	return 404
}

func (o *ListMilestoneEpicsNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v3/milestones/{milestone-public-id}/epics][%d] listMilestoneEpicsNotFound", 404)
}

func (o *ListMilestoneEpicsNotFound) String() string {
	return fmt.Sprintf("[GET /api/v3/milestones/{milestone-public-id}/epics][%d] listMilestoneEpicsNotFound", 404)
}

func (o *ListMilestoneEpicsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewListMilestoneEpicsUnprocessableEntity creates a ListMilestoneEpicsUnprocessableEntity with default headers values
func NewListMilestoneEpicsUnprocessableEntity() *ListMilestoneEpicsUnprocessableEntity {
	return &ListMilestoneEpicsUnprocessableEntity{}
}

/*
ListMilestoneEpicsUnprocessableEntity describes a response with status code 422, with default header values.

Unprocessable
*/
type ListMilestoneEpicsUnprocessableEntity struct {
}

// IsSuccess returns true when this list milestone epics unprocessable entity response has a 2xx status code
func (o *ListMilestoneEpicsUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list milestone epics unprocessable entity response has a 3xx status code
func (o *ListMilestoneEpicsUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list milestone epics unprocessable entity response has a 4xx status code
func (o *ListMilestoneEpicsUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this list milestone epics unprocessable entity response has a 5xx status code
func (o *ListMilestoneEpicsUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this list milestone epics unprocessable entity response a status code equal to that given
func (o *ListMilestoneEpicsUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

// Code gets the status code for the list milestone epics unprocessable entity response
func (o *ListMilestoneEpicsUnprocessableEntity) Code() int {
	return 422
}

func (o *ListMilestoneEpicsUnprocessableEntity) Error() string {
	return fmt.Sprintf("[GET /api/v3/milestones/{milestone-public-id}/epics][%d] listMilestoneEpicsUnprocessableEntity", 422)
}

func (o *ListMilestoneEpicsUnprocessableEntity) String() string {
	return fmt.Sprintf("[GET /api/v3/milestones/{milestone-public-id}/epics][%d] listMilestoneEpicsUnprocessableEntity", 422)
}

func (o *ListMilestoneEpicsUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
