// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/FindHotel/shortcut-go/models"
)

// ListCategoryObjectivesReader is a Reader for the ListCategoryObjectives structure.
type ListCategoryObjectivesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListCategoryObjectivesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListCategoryObjectivesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewListCategoryObjectivesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewListCategoryObjectivesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewListCategoryObjectivesUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/v3/categories/{category-public-id}/objectives] listCategoryObjectives", response, response.Code())
	}
}

// NewListCategoryObjectivesOK creates a ListCategoryObjectivesOK with default headers values
func NewListCategoryObjectivesOK() *ListCategoryObjectivesOK {
	return &ListCategoryObjectivesOK{}
}

/*
ListCategoryObjectivesOK describes a response with status code 200, with default header values.

Resource
*/
type ListCategoryObjectivesOK struct {
	Payload []*models.Milestone
}

// IsSuccess returns true when this list category objectives o k response has a 2xx status code
func (o *ListCategoryObjectivesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list category objectives o k response has a 3xx status code
func (o *ListCategoryObjectivesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list category objectives o k response has a 4xx status code
func (o *ListCategoryObjectivesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list category objectives o k response has a 5xx status code
func (o *ListCategoryObjectivesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list category objectives o k response a status code equal to that given
func (o *ListCategoryObjectivesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list category objectives o k response
func (o *ListCategoryObjectivesOK) Code() int {
	return 200
}

func (o *ListCategoryObjectivesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v3/categories/{category-public-id}/objectives][%d] listCategoryObjectivesOK %s", 200, payload)
}

func (o *ListCategoryObjectivesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v3/categories/{category-public-id}/objectives][%d] listCategoryObjectivesOK %s", 200, payload)
}

func (o *ListCategoryObjectivesOK) GetPayload() []*models.Milestone {
	return o.Payload
}

func (o *ListCategoryObjectivesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListCategoryObjectivesBadRequest creates a ListCategoryObjectivesBadRequest with default headers values
func NewListCategoryObjectivesBadRequest() *ListCategoryObjectivesBadRequest {
	return &ListCategoryObjectivesBadRequest{}
}

/*
ListCategoryObjectivesBadRequest describes a response with status code 400, with default header values.

Schema mismatch
*/
type ListCategoryObjectivesBadRequest struct {
}

// IsSuccess returns true when this list category objectives bad request response has a 2xx status code
func (o *ListCategoryObjectivesBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list category objectives bad request response has a 3xx status code
func (o *ListCategoryObjectivesBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list category objectives bad request response has a 4xx status code
func (o *ListCategoryObjectivesBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this list category objectives bad request response has a 5xx status code
func (o *ListCategoryObjectivesBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this list category objectives bad request response a status code equal to that given
func (o *ListCategoryObjectivesBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the list category objectives bad request response
func (o *ListCategoryObjectivesBadRequest) Code() int {
	return 400
}

func (o *ListCategoryObjectivesBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/v3/categories/{category-public-id}/objectives][%d] listCategoryObjectivesBadRequest", 400)
}

func (o *ListCategoryObjectivesBadRequest) String() string {
	return fmt.Sprintf("[GET /api/v3/categories/{category-public-id}/objectives][%d] listCategoryObjectivesBadRequest", 400)
}

func (o *ListCategoryObjectivesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewListCategoryObjectivesNotFound creates a ListCategoryObjectivesNotFound with default headers values
func NewListCategoryObjectivesNotFound() *ListCategoryObjectivesNotFound {
	return &ListCategoryObjectivesNotFound{}
}

/*
ListCategoryObjectivesNotFound describes a response with status code 404, with default header values.

Resource does not exist
*/
type ListCategoryObjectivesNotFound struct {
}

// IsSuccess returns true when this list category objectives not found response has a 2xx status code
func (o *ListCategoryObjectivesNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list category objectives not found response has a 3xx status code
func (o *ListCategoryObjectivesNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list category objectives not found response has a 4xx status code
func (o *ListCategoryObjectivesNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this list category objectives not found response has a 5xx status code
func (o *ListCategoryObjectivesNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this list category objectives not found response a status code equal to that given
func (o *ListCategoryObjectivesNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the list category objectives not found response
func (o *ListCategoryObjectivesNotFound) Code() int {
	return 404
}

func (o *ListCategoryObjectivesNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v3/categories/{category-public-id}/objectives][%d] listCategoryObjectivesNotFound", 404)
}

func (o *ListCategoryObjectivesNotFound) String() string {
	return fmt.Sprintf("[GET /api/v3/categories/{category-public-id}/objectives][%d] listCategoryObjectivesNotFound", 404)
}

func (o *ListCategoryObjectivesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewListCategoryObjectivesUnprocessableEntity creates a ListCategoryObjectivesUnprocessableEntity with default headers values
func NewListCategoryObjectivesUnprocessableEntity() *ListCategoryObjectivesUnprocessableEntity {
	return &ListCategoryObjectivesUnprocessableEntity{}
}

/*
ListCategoryObjectivesUnprocessableEntity describes a response with status code 422, with default header values.

Unprocessable
*/
type ListCategoryObjectivesUnprocessableEntity struct {
}

// IsSuccess returns true when this list category objectives unprocessable entity response has a 2xx status code
func (o *ListCategoryObjectivesUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list category objectives unprocessable entity response has a 3xx status code
func (o *ListCategoryObjectivesUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list category objectives unprocessable entity response has a 4xx status code
func (o *ListCategoryObjectivesUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this list category objectives unprocessable entity response has a 5xx status code
func (o *ListCategoryObjectivesUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this list category objectives unprocessable entity response a status code equal to that given
func (o *ListCategoryObjectivesUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

// Code gets the status code for the list category objectives unprocessable entity response
func (o *ListCategoryObjectivesUnprocessableEntity) Code() int {
	return 422
}

func (o *ListCategoryObjectivesUnprocessableEntity) Error() string {
	return fmt.Sprintf("[GET /api/v3/categories/{category-public-id}/objectives][%d] listCategoryObjectivesUnprocessableEntity", 422)
}

func (o *ListCategoryObjectivesUnprocessableEntity) String() string {
	return fmt.Sprintf("[GET /api/v3/categories/{category-public-id}/objectives][%d] listCategoryObjectivesUnprocessableEntity", 422)
}

func (o *ListCategoryObjectivesUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
