// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/FindHotel/shortcut-go/models"
)

// ListGroupsReader is a Reader for the ListGroups structure.
type ListGroupsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListGroupsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListGroupsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewListGroupsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewListGroupsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewListGroupsUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListGroupsOK creates a ListGroupsOK with default headers values
func NewListGroupsOK() *ListGroupsOK {
	return &ListGroupsOK{}
}

/*
ListGroupsOK describes a response with status code 200, with default header values.

Resource
*/
type ListGroupsOK struct {
	Payload []*models.Group
}

// IsSuccess returns true when this list groups o k response has a 2xx status code
func (o *ListGroupsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list groups o k response has a 3xx status code
func (o *ListGroupsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list groups o k response has a 4xx status code
func (o *ListGroupsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list groups o k response has a 5xx status code
func (o *ListGroupsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list groups o k response a status code equal to that given
func (o *ListGroupsOK) IsCode(code int) bool {
	return code == 200
}

func (o *ListGroupsOK) Error() string {
	return fmt.Sprintf("[GET /api/v3/groups][%d] listGroupsOK  %+v", 200, o.Payload)
}

func (o *ListGroupsOK) String() string {
	return fmt.Sprintf("[GET /api/v3/groups][%d] listGroupsOK  %+v", 200, o.Payload)
}

func (o *ListGroupsOK) GetPayload() []*models.Group {
	return o.Payload
}

func (o *ListGroupsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListGroupsBadRequest creates a ListGroupsBadRequest with default headers values
func NewListGroupsBadRequest() *ListGroupsBadRequest {
	return &ListGroupsBadRequest{}
}

/*
ListGroupsBadRequest describes a response with status code 400, with default header values.

Schema mismatch
*/
type ListGroupsBadRequest struct {
}

// IsSuccess returns true when this list groups bad request response has a 2xx status code
func (o *ListGroupsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list groups bad request response has a 3xx status code
func (o *ListGroupsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list groups bad request response has a 4xx status code
func (o *ListGroupsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this list groups bad request response has a 5xx status code
func (o *ListGroupsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this list groups bad request response a status code equal to that given
func (o *ListGroupsBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *ListGroupsBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/v3/groups][%d] listGroupsBadRequest ", 400)
}

func (o *ListGroupsBadRequest) String() string {
	return fmt.Sprintf("[GET /api/v3/groups][%d] listGroupsBadRequest ", 400)
}

func (o *ListGroupsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewListGroupsNotFound creates a ListGroupsNotFound with default headers values
func NewListGroupsNotFound() *ListGroupsNotFound {
	return &ListGroupsNotFound{}
}

/*
ListGroupsNotFound describes a response with status code 404, with default header values.

Resource does not exist
*/
type ListGroupsNotFound struct {
}

// IsSuccess returns true when this list groups not found response has a 2xx status code
func (o *ListGroupsNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list groups not found response has a 3xx status code
func (o *ListGroupsNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list groups not found response has a 4xx status code
func (o *ListGroupsNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this list groups not found response has a 5xx status code
func (o *ListGroupsNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this list groups not found response a status code equal to that given
func (o *ListGroupsNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *ListGroupsNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v3/groups][%d] listGroupsNotFound ", 404)
}

func (o *ListGroupsNotFound) String() string {
	return fmt.Sprintf("[GET /api/v3/groups][%d] listGroupsNotFound ", 404)
}

func (o *ListGroupsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewListGroupsUnprocessableEntity creates a ListGroupsUnprocessableEntity with default headers values
func NewListGroupsUnprocessableEntity() *ListGroupsUnprocessableEntity {
	return &ListGroupsUnprocessableEntity{}
}

/*
ListGroupsUnprocessableEntity describes a response with status code 422, with default header values.

Unprocessable
*/
type ListGroupsUnprocessableEntity struct {
}

// IsSuccess returns true when this list groups unprocessable entity response has a 2xx status code
func (o *ListGroupsUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list groups unprocessable entity response has a 3xx status code
func (o *ListGroupsUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list groups unprocessable entity response has a 4xx status code
func (o *ListGroupsUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this list groups unprocessable entity response has a 5xx status code
func (o *ListGroupsUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this list groups unprocessable entity response a status code equal to that given
func (o *ListGroupsUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

func (o *ListGroupsUnprocessableEntity) Error() string {
	return fmt.Sprintf("[GET /api/v3/groups][%d] listGroupsUnprocessableEntity ", 422)
}

func (o *ListGroupsUnprocessableEntity) String() string {
	return fmt.Sprintf("[GET /api/v3/groups][%d] listGroupsUnprocessableEntity ", 422)
}

func (o *ListGroupsUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
