// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/FindHotel/shortcut-go/models"
)

// NewSearchMilestonesParams creates a new SearchMilestonesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSearchMilestonesParams() *SearchMilestonesParams {
	return &SearchMilestonesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSearchMilestonesParamsWithTimeout creates a new SearchMilestonesParams object
// with the ability to set a timeout on a request.
func NewSearchMilestonesParamsWithTimeout(timeout time.Duration) *SearchMilestonesParams {
	return &SearchMilestonesParams{
		timeout: timeout,
	}
}

// NewSearchMilestonesParamsWithContext creates a new SearchMilestonesParams object
// with the ability to set a context for a request.
func NewSearchMilestonesParamsWithContext(ctx context.Context) *SearchMilestonesParams {
	return &SearchMilestonesParams{
		Context: ctx,
	}
}

// NewSearchMilestonesParamsWithHTTPClient creates a new SearchMilestonesParams object
// with the ability to set a custom HTTPClient for a request.
func NewSearchMilestonesParamsWithHTTPClient(client *http.Client) *SearchMilestonesParams {
	return &SearchMilestonesParams{
		HTTPClient: client,
	}
}

/*
SearchMilestonesParams contains all the parameters to send to the API endpoint

	for the search milestones operation.

	Typically these are written to a http.Request.
*/
type SearchMilestonesParams struct {

	// Search.
	Search *models.Search

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the search milestones params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SearchMilestonesParams) WithDefaults() *SearchMilestonesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the search milestones params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SearchMilestonesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the search milestones params
func (o *SearchMilestonesParams) WithTimeout(timeout time.Duration) *SearchMilestonesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the search milestones params
func (o *SearchMilestonesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the search milestones params
func (o *SearchMilestonesParams) WithContext(ctx context.Context) *SearchMilestonesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the search milestones params
func (o *SearchMilestonesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the search milestones params
func (o *SearchMilestonesParams) WithHTTPClient(client *http.Client) *SearchMilestonesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the search milestones params
func (o *SearchMilestonesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSearch adds the search to the search milestones params
func (o *SearchMilestonesParams) WithSearch(search *models.Search) *SearchMilestonesParams {
	o.SetSearch(search)
	return o
}

// SetSearch adds the search to the search milestones params
func (o *SearchMilestonesParams) SetSearch(search *models.Search) {
	o.Search = search
}

// WriteToRequest writes these params to a swagger request
func (o *SearchMilestonesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Search != nil {
		if err := r.SetBodyParam(o.Search); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
