// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/FindHotel/shortcut-go/models"
)

// NewSearchIterationsParams creates a new SearchIterationsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSearchIterationsParams() *SearchIterationsParams {
	return &SearchIterationsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSearchIterationsParamsWithTimeout creates a new SearchIterationsParams object
// with the ability to set a timeout on a request.
func NewSearchIterationsParamsWithTimeout(timeout time.Duration) *SearchIterationsParams {
	return &SearchIterationsParams{
		timeout: timeout,
	}
}

// NewSearchIterationsParamsWithContext creates a new SearchIterationsParams object
// with the ability to set a context for a request.
func NewSearchIterationsParamsWithContext(ctx context.Context) *SearchIterationsParams {
	return &SearchIterationsParams{
		Context: ctx,
	}
}

// NewSearchIterationsParamsWithHTTPClient creates a new SearchIterationsParams object
// with the ability to set a custom HTTPClient for a request.
func NewSearchIterationsParamsWithHTTPClient(client *http.Client) *SearchIterationsParams {
	return &SearchIterationsParams{
		HTTPClient: client,
	}
}

/*
SearchIterationsParams contains all the parameters to send to the API endpoint

	for the search iterations operation.

	Typically these are written to a http.Request.
*/
type SearchIterationsParams struct {

	// Search.
	Search *models.Search

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the search iterations params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SearchIterationsParams) WithDefaults() *SearchIterationsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the search iterations params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SearchIterationsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the search iterations params
func (o *SearchIterationsParams) WithTimeout(timeout time.Duration) *SearchIterationsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the search iterations params
func (o *SearchIterationsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the search iterations params
func (o *SearchIterationsParams) WithContext(ctx context.Context) *SearchIterationsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the search iterations params
func (o *SearchIterationsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the search iterations params
func (o *SearchIterationsParams) WithHTTPClient(client *http.Client) *SearchIterationsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the search iterations params
func (o *SearchIterationsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSearch adds the search to the search iterations params
func (o *SearchIterationsParams) WithSearch(search *models.Search) *SearchIterationsParams {
	o.SetSearch(search)
	return o
}

// SetSearch adds the search to the search iterations params
func (o *SearchIterationsParams) SetSearch(search *models.Search) {
	o.Search = search
}

// WriteToRequest writes these params to a swagger request
func (o *SearchIterationsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Search != nil {
		if err := r.SetBodyParam(o.Search); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
