// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/FindHotel/shortcut-go/models"
)

// StoryHistoryReader is a Reader for the StoryHistory structure.
type StoryHistoryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *StoryHistoryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewStoryHistoryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewStoryHistoryBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewStoryHistoryNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewStoryHistoryUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/v3/stories/{story-public-id}/history] storyHistory", response, response.Code())
	}
}

// NewStoryHistoryOK creates a StoryHistoryOK with default headers values
func NewStoryHistoryOK() *StoryHistoryOK {
	return &StoryHistoryOK{}
}

/*
StoryHistoryOK describes a response with status code 200, with default header values.

Resource
*/
type StoryHistoryOK struct {
	Payload []*models.History
}

// IsSuccess returns true when this story history o k response has a 2xx status code
func (o *StoryHistoryOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this story history o k response has a 3xx status code
func (o *StoryHistoryOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this story history o k response has a 4xx status code
func (o *StoryHistoryOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this story history o k response has a 5xx status code
func (o *StoryHistoryOK) IsServerError() bool {
	return false
}

// IsCode returns true when this story history o k response a status code equal to that given
func (o *StoryHistoryOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the story history o k response
func (o *StoryHistoryOK) Code() int {
	return 200
}

func (o *StoryHistoryOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v3/stories/{story-public-id}/history][%d] storyHistoryOK %s", 200, payload)
}

func (o *StoryHistoryOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v3/stories/{story-public-id}/history][%d] storyHistoryOK %s", 200, payload)
}

func (o *StoryHistoryOK) GetPayload() []*models.History {
	return o.Payload
}

func (o *StoryHistoryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewStoryHistoryBadRequest creates a StoryHistoryBadRequest with default headers values
func NewStoryHistoryBadRequest() *StoryHistoryBadRequest {
	return &StoryHistoryBadRequest{}
}

/*
StoryHistoryBadRequest describes a response with status code 400, with default header values.

Schema mismatch
*/
type StoryHistoryBadRequest struct {
}

// IsSuccess returns true when this story history bad request response has a 2xx status code
func (o *StoryHistoryBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this story history bad request response has a 3xx status code
func (o *StoryHistoryBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this story history bad request response has a 4xx status code
func (o *StoryHistoryBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this story history bad request response has a 5xx status code
func (o *StoryHistoryBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this story history bad request response a status code equal to that given
func (o *StoryHistoryBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the story history bad request response
func (o *StoryHistoryBadRequest) Code() int {
	return 400
}

func (o *StoryHistoryBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/v3/stories/{story-public-id}/history][%d] storyHistoryBadRequest", 400)
}

func (o *StoryHistoryBadRequest) String() string {
	return fmt.Sprintf("[GET /api/v3/stories/{story-public-id}/history][%d] storyHistoryBadRequest", 400)
}

func (o *StoryHistoryBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewStoryHistoryNotFound creates a StoryHistoryNotFound with default headers values
func NewStoryHistoryNotFound() *StoryHistoryNotFound {
	return &StoryHistoryNotFound{}
}

/*
StoryHistoryNotFound describes a response with status code 404, with default header values.

Resource does not exist
*/
type StoryHistoryNotFound struct {
}

// IsSuccess returns true when this story history not found response has a 2xx status code
func (o *StoryHistoryNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this story history not found response has a 3xx status code
func (o *StoryHistoryNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this story history not found response has a 4xx status code
func (o *StoryHistoryNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this story history not found response has a 5xx status code
func (o *StoryHistoryNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this story history not found response a status code equal to that given
func (o *StoryHistoryNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the story history not found response
func (o *StoryHistoryNotFound) Code() int {
	return 404
}

func (o *StoryHistoryNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v3/stories/{story-public-id}/history][%d] storyHistoryNotFound", 404)
}

func (o *StoryHistoryNotFound) String() string {
	return fmt.Sprintf("[GET /api/v3/stories/{story-public-id}/history][%d] storyHistoryNotFound", 404)
}

func (o *StoryHistoryNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewStoryHistoryUnprocessableEntity creates a StoryHistoryUnprocessableEntity with default headers values
func NewStoryHistoryUnprocessableEntity() *StoryHistoryUnprocessableEntity {
	return &StoryHistoryUnprocessableEntity{}
}

/*
StoryHistoryUnprocessableEntity describes a response with status code 422, with default header values.

Unprocessable
*/
type StoryHistoryUnprocessableEntity struct {
}

// IsSuccess returns true when this story history unprocessable entity response has a 2xx status code
func (o *StoryHistoryUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this story history unprocessable entity response has a 3xx status code
func (o *StoryHistoryUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this story history unprocessable entity response has a 4xx status code
func (o *StoryHistoryUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this story history unprocessable entity response has a 5xx status code
func (o *StoryHistoryUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this story history unprocessable entity response a status code equal to that given
func (o *StoryHistoryUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

// Code gets the status code for the story history unprocessable entity response
func (o *StoryHistoryUnprocessableEntity) Code() int {
	return 422
}

func (o *StoryHistoryUnprocessableEntity) Error() string {
	return fmt.Sprintf("[GET /api/v3/stories/{story-public-id}/history][%d] storyHistoryUnprocessableEntity", 422)
}

func (o *StoryHistoryUnprocessableEntity) String() string {
	return fmt.Sprintf("[GET /api/v3/stories/{story-public-id}/history][%d] storyHistoryUnprocessableEntity", 422)
}

func (o *StoryHistoryUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
