// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/FindHotel/shortcut-go/models"
)

// UpdateEntityTemplateReader is a Reader for the UpdateEntityTemplate structure.
type UpdateEntityTemplateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateEntityTemplateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateEntityTemplateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUpdateEntityTemplateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewUpdateEntityTemplateNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewUpdateEntityTemplateUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PUT /api/v3/entity-templates/{entity-template-public-id}] updateEntityTemplate", response, response.Code())
	}
}

// NewUpdateEntityTemplateOK creates a UpdateEntityTemplateOK with default headers values
func NewUpdateEntityTemplateOK() *UpdateEntityTemplateOK {
	return &UpdateEntityTemplateOK{}
}

/*
UpdateEntityTemplateOK describes a response with status code 200, with default header values.

Resource
*/
type UpdateEntityTemplateOK struct {
	Payload *models.EntityTemplate
}

// IsSuccess returns true when this update entity template o k response has a 2xx status code
func (o *UpdateEntityTemplateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this update entity template o k response has a 3xx status code
func (o *UpdateEntityTemplateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update entity template o k response has a 4xx status code
func (o *UpdateEntityTemplateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this update entity template o k response has a 5xx status code
func (o *UpdateEntityTemplateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this update entity template o k response a status code equal to that given
func (o *UpdateEntityTemplateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the update entity template o k response
func (o *UpdateEntityTemplateOK) Code() int {
	return 200
}

func (o *UpdateEntityTemplateOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/v3/entity-templates/{entity-template-public-id}][%d] updateEntityTemplateOK %s", 200, payload)
}

func (o *UpdateEntityTemplateOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/v3/entity-templates/{entity-template-public-id}][%d] updateEntityTemplateOK %s", 200, payload)
}

func (o *UpdateEntityTemplateOK) GetPayload() *models.EntityTemplate {
	return o.Payload
}

func (o *UpdateEntityTemplateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EntityTemplate)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateEntityTemplateBadRequest creates a UpdateEntityTemplateBadRequest with default headers values
func NewUpdateEntityTemplateBadRequest() *UpdateEntityTemplateBadRequest {
	return &UpdateEntityTemplateBadRequest{}
}

/*
UpdateEntityTemplateBadRequest describes a response with status code 400, with default header values.

Schema mismatch
*/
type UpdateEntityTemplateBadRequest struct {
}

// IsSuccess returns true when this update entity template bad request response has a 2xx status code
func (o *UpdateEntityTemplateBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update entity template bad request response has a 3xx status code
func (o *UpdateEntityTemplateBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update entity template bad request response has a 4xx status code
func (o *UpdateEntityTemplateBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this update entity template bad request response has a 5xx status code
func (o *UpdateEntityTemplateBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this update entity template bad request response a status code equal to that given
func (o *UpdateEntityTemplateBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the update entity template bad request response
func (o *UpdateEntityTemplateBadRequest) Code() int {
	return 400
}

func (o *UpdateEntityTemplateBadRequest) Error() string {
	return fmt.Sprintf("[PUT /api/v3/entity-templates/{entity-template-public-id}][%d] updateEntityTemplateBadRequest", 400)
}

func (o *UpdateEntityTemplateBadRequest) String() string {
	return fmt.Sprintf("[PUT /api/v3/entity-templates/{entity-template-public-id}][%d] updateEntityTemplateBadRequest", 400)
}

func (o *UpdateEntityTemplateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateEntityTemplateNotFound creates a UpdateEntityTemplateNotFound with default headers values
func NewUpdateEntityTemplateNotFound() *UpdateEntityTemplateNotFound {
	return &UpdateEntityTemplateNotFound{}
}

/*
UpdateEntityTemplateNotFound describes a response with status code 404, with default header values.

Resource does not exist
*/
type UpdateEntityTemplateNotFound struct {
}

// IsSuccess returns true when this update entity template not found response has a 2xx status code
func (o *UpdateEntityTemplateNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update entity template not found response has a 3xx status code
func (o *UpdateEntityTemplateNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update entity template not found response has a 4xx status code
func (o *UpdateEntityTemplateNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this update entity template not found response has a 5xx status code
func (o *UpdateEntityTemplateNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this update entity template not found response a status code equal to that given
func (o *UpdateEntityTemplateNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the update entity template not found response
func (o *UpdateEntityTemplateNotFound) Code() int {
	return 404
}

func (o *UpdateEntityTemplateNotFound) Error() string {
	return fmt.Sprintf("[PUT /api/v3/entity-templates/{entity-template-public-id}][%d] updateEntityTemplateNotFound", 404)
}

func (o *UpdateEntityTemplateNotFound) String() string {
	return fmt.Sprintf("[PUT /api/v3/entity-templates/{entity-template-public-id}][%d] updateEntityTemplateNotFound", 404)
}

func (o *UpdateEntityTemplateNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateEntityTemplateUnprocessableEntity creates a UpdateEntityTemplateUnprocessableEntity with default headers values
func NewUpdateEntityTemplateUnprocessableEntity() *UpdateEntityTemplateUnprocessableEntity {
	return &UpdateEntityTemplateUnprocessableEntity{}
}

/*
UpdateEntityTemplateUnprocessableEntity describes a response with status code 422, with default header values.

Unprocessable
*/
type UpdateEntityTemplateUnprocessableEntity struct {
}

// IsSuccess returns true when this update entity template unprocessable entity response has a 2xx status code
func (o *UpdateEntityTemplateUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update entity template unprocessable entity response has a 3xx status code
func (o *UpdateEntityTemplateUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update entity template unprocessable entity response has a 4xx status code
func (o *UpdateEntityTemplateUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this update entity template unprocessable entity response has a 5xx status code
func (o *UpdateEntityTemplateUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this update entity template unprocessable entity response a status code equal to that given
func (o *UpdateEntityTemplateUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

// Code gets the status code for the update entity template unprocessable entity response
func (o *UpdateEntityTemplateUnprocessableEntity) Code() int {
	return 422
}

func (o *UpdateEntityTemplateUnprocessableEntity) Error() string {
	return fmt.Sprintf("[PUT /api/v3/entity-templates/{entity-template-public-id}][%d] updateEntityTemplateUnprocessableEntity", 422)
}

func (o *UpdateEntityTemplateUnprocessableEntity) String() string {
	return fmt.Sprintf("[PUT /api/v3/entity-templates/{entity-template-public-id}][%d] updateEntityTemplateUnprocessableEntity", 422)
}

func (o *UpdateEntityTemplateUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
