// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/FindHotel/shortcut-go/models"
)

// UpdateLabelReader is a Reader for the UpdateLabel structure.
type UpdateLabelReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateLabelReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateLabelOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUpdateLabelBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewUpdateLabelNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewUpdateLabelUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUpdateLabelOK creates a UpdateLabelOK with default headers values
func NewUpdateLabelOK() *UpdateLabelOK {
	return &UpdateLabelOK{}
}

/*
UpdateLabelOK describes a response with status code 200, with default header values.

Resource
*/
type UpdateLabelOK struct {
	Payload *models.Label
}

// IsSuccess returns true when this update label o k response has a 2xx status code
func (o *UpdateLabelOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this update label o k response has a 3xx status code
func (o *UpdateLabelOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update label o k response has a 4xx status code
func (o *UpdateLabelOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this update label o k response has a 5xx status code
func (o *UpdateLabelOK) IsServerError() bool {
	return false
}

// IsCode returns true when this update label o k response a status code equal to that given
func (o *UpdateLabelOK) IsCode(code int) bool {
	return code == 200
}

func (o *UpdateLabelOK) Error() string {
	return fmt.Sprintf("[PUT /api/v3/labels/{label-public-id}][%d] updateLabelOK  %+v", 200, o.Payload)
}

func (o *UpdateLabelOK) String() string {
	return fmt.Sprintf("[PUT /api/v3/labels/{label-public-id}][%d] updateLabelOK  %+v", 200, o.Payload)
}

func (o *UpdateLabelOK) GetPayload() *models.Label {
	return o.Payload
}

func (o *UpdateLabelOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Label)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateLabelBadRequest creates a UpdateLabelBadRequest with default headers values
func NewUpdateLabelBadRequest() *UpdateLabelBadRequest {
	return &UpdateLabelBadRequest{}
}

/*
UpdateLabelBadRequest describes a response with status code 400, with default header values.

Schema mismatch
*/
type UpdateLabelBadRequest struct {
}

// IsSuccess returns true when this update label bad request response has a 2xx status code
func (o *UpdateLabelBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update label bad request response has a 3xx status code
func (o *UpdateLabelBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update label bad request response has a 4xx status code
func (o *UpdateLabelBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this update label bad request response has a 5xx status code
func (o *UpdateLabelBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this update label bad request response a status code equal to that given
func (o *UpdateLabelBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *UpdateLabelBadRequest) Error() string {
	return fmt.Sprintf("[PUT /api/v3/labels/{label-public-id}][%d] updateLabelBadRequest ", 400)
}

func (o *UpdateLabelBadRequest) String() string {
	return fmt.Sprintf("[PUT /api/v3/labels/{label-public-id}][%d] updateLabelBadRequest ", 400)
}

func (o *UpdateLabelBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateLabelNotFound creates a UpdateLabelNotFound with default headers values
func NewUpdateLabelNotFound() *UpdateLabelNotFound {
	return &UpdateLabelNotFound{}
}

/*
UpdateLabelNotFound describes a response with status code 404, with default header values.

Resource does not exist
*/
type UpdateLabelNotFound struct {
}

// IsSuccess returns true when this update label not found response has a 2xx status code
func (o *UpdateLabelNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update label not found response has a 3xx status code
func (o *UpdateLabelNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update label not found response has a 4xx status code
func (o *UpdateLabelNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this update label not found response has a 5xx status code
func (o *UpdateLabelNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this update label not found response a status code equal to that given
func (o *UpdateLabelNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *UpdateLabelNotFound) Error() string {
	return fmt.Sprintf("[PUT /api/v3/labels/{label-public-id}][%d] updateLabelNotFound ", 404)
}

func (o *UpdateLabelNotFound) String() string {
	return fmt.Sprintf("[PUT /api/v3/labels/{label-public-id}][%d] updateLabelNotFound ", 404)
}

func (o *UpdateLabelNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateLabelUnprocessableEntity creates a UpdateLabelUnprocessableEntity with default headers values
func NewUpdateLabelUnprocessableEntity() *UpdateLabelUnprocessableEntity {
	return &UpdateLabelUnprocessableEntity{}
}

/*
UpdateLabelUnprocessableEntity describes a response with status code 422, with default header values.

Unprocessable
*/
type UpdateLabelUnprocessableEntity struct {
}

// IsSuccess returns true when this update label unprocessable entity response has a 2xx status code
func (o *UpdateLabelUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update label unprocessable entity response has a 3xx status code
func (o *UpdateLabelUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update label unprocessable entity response has a 4xx status code
func (o *UpdateLabelUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this update label unprocessable entity response has a 5xx status code
func (o *UpdateLabelUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this update label unprocessable entity response a status code equal to that given
func (o *UpdateLabelUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

func (o *UpdateLabelUnprocessableEntity) Error() string {
	return fmt.Sprintf("[PUT /api/v3/labels/{label-public-id}][%d] updateLabelUnprocessableEntity ", 422)
}

func (o *UpdateLabelUnprocessableEntity) String() string {
	return fmt.Sprintf("[PUT /api/v3/labels/{label-public-id}][%d] updateLabelUnprocessableEntity ", 422)
}

func (o *UpdateLabelUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
