// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/FindHotel/shortcut-go/models"
)

// UploadFilesReader is a Reader for the UploadFiles structure.
type UploadFilesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UploadFilesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewUploadFilesCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUploadFilesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewUploadFilesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewUploadFilesUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUploadFilesCreated creates a UploadFilesCreated with default headers values
func NewUploadFilesCreated() *UploadFilesCreated {
	return &UploadFilesCreated{}
}

/*
UploadFilesCreated describes a response with status code 201, with default header values.

Resource
*/
type UploadFilesCreated struct {
	Payload []*models.UploadedFile
}

// IsSuccess returns true when this upload files created response has a 2xx status code
func (o *UploadFilesCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this upload files created response has a 3xx status code
func (o *UploadFilesCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this upload files created response has a 4xx status code
func (o *UploadFilesCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this upload files created response has a 5xx status code
func (o *UploadFilesCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this upload files created response a status code equal to that given
func (o *UploadFilesCreated) IsCode(code int) bool {
	return code == 201
}

func (o *UploadFilesCreated) Error() string {
	return fmt.Sprintf("[POST /api/v3/files][%d] uploadFilesCreated  %+v", 201, o.Payload)
}

func (o *UploadFilesCreated) String() string {
	return fmt.Sprintf("[POST /api/v3/files][%d] uploadFilesCreated  %+v", 201, o.Payload)
}

func (o *UploadFilesCreated) GetPayload() []*models.UploadedFile {
	return o.Payload
}

func (o *UploadFilesCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUploadFilesBadRequest creates a UploadFilesBadRequest with default headers values
func NewUploadFilesBadRequest() *UploadFilesBadRequest {
	return &UploadFilesBadRequest{}
}

/*
UploadFilesBadRequest describes a response with status code 400, with default header values.

Schema mismatch
*/
type UploadFilesBadRequest struct {
}

// IsSuccess returns true when this upload files bad request response has a 2xx status code
func (o *UploadFilesBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this upload files bad request response has a 3xx status code
func (o *UploadFilesBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this upload files bad request response has a 4xx status code
func (o *UploadFilesBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this upload files bad request response has a 5xx status code
func (o *UploadFilesBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this upload files bad request response a status code equal to that given
func (o *UploadFilesBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *UploadFilesBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/v3/files][%d] uploadFilesBadRequest ", 400)
}

func (o *UploadFilesBadRequest) String() string {
	return fmt.Sprintf("[POST /api/v3/files][%d] uploadFilesBadRequest ", 400)
}

func (o *UploadFilesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUploadFilesNotFound creates a UploadFilesNotFound with default headers values
func NewUploadFilesNotFound() *UploadFilesNotFound {
	return &UploadFilesNotFound{}
}

/*
UploadFilesNotFound describes a response with status code 404, with default header values.

Resource does not exist
*/
type UploadFilesNotFound struct {
}

// IsSuccess returns true when this upload files not found response has a 2xx status code
func (o *UploadFilesNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this upload files not found response has a 3xx status code
func (o *UploadFilesNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this upload files not found response has a 4xx status code
func (o *UploadFilesNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this upload files not found response has a 5xx status code
func (o *UploadFilesNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this upload files not found response a status code equal to that given
func (o *UploadFilesNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *UploadFilesNotFound) Error() string {
	return fmt.Sprintf("[POST /api/v3/files][%d] uploadFilesNotFound ", 404)
}

func (o *UploadFilesNotFound) String() string {
	return fmt.Sprintf("[POST /api/v3/files][%d] uploadFilesNotFound ", 404)
}

func (o *UploadFilesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUploadFilesUnprocessableEntity creates a UploadFilesUnprocessableEntity with default headers values
func NewUploadFilesUnprocessableEntity() *UploadFilesUnprocessableEntity {
	return &UploadFilesUnprocessableEntity{}
}

/*
UploadFilesUnprocessableEntity describes a response with status code 422, with default header values.

Unprocessable
*/
type UploadFilesUnprocessableEntity struct {
}

// IsSuccess returns true when this upload files unprocessable entity response has a 2xx status code
func (o *UploadFilesUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this upload files unprocessable entity response has a 3xx status code
func (o *UploadFilesUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this upload files unprocessable entity response has a 4xx status code
func (o *UploadFilesUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this upload files unprocessable entity response has a 5xx status code
func (o *UploadFilesUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this upload files unprocessable entity response a status code equal to that given
func (o *UploadFilesUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

func (o *UploadFilesUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /api/v3/files][%d] uploadFilesUnprocessableEntity ", 422)
}

func (o *UploadFilesUnprocessableEntity) String() string {
	return fmt.Sprintf("[POST /api/v3/files][%d] uploadFilesUnprocessableEntity ", 422)
}

func (o *UploadFilesUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
