// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// EpicAssociatedGroup epic associated group
//
// swagger:model EpicAssociatedGroup
type EpicAssociatedGroup struct {

	// The number of stories this Group owns in the Epic.
	AssociatedStoriesCount int64 `json:"associated_stories_count,omitempty"`

	// The Group ID of the associated group.
	// Required: true
	// Format: uuid
	GroupID *strfmt.UUID `json:"group_id"`
}

// Validate validates this epic associated group
func (m *EpicAssociatedGroup) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateGroupID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *EpicAssociatedGroup) validateGroupID(formats strfmt.Registry) error {

	if err := validate.Required("group_id", "body", m.GroupID); err != nil {
		return err
	}

	if err := validate.FormatOf("group_id", "body", "uuid", m.GroupID.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this epic associated group based on context it is used
func (m *EpicAssociatedGroup) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *EpicAssociatedGroup) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EpicAssociatedGroup) UnmarshalBinary(b []byte) error {
	var res EpicAssociatedGroup
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
