// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// StoryCustomField story custom field
//
// swagger:model StoryCustomField
type StoryCustomField struct {

	// The unique public ID for a CustomField.
	// Required: true
	// Format: uuid
	FieldID *strfmt.UUID `json:"field_id"`

	// A string representation of the value, if applicable.
	// Required: true
	Value *string `json:"value"`

	// The unique public ID for a CustomFieldEnumValue.
	// Required: true
	// Format: uuid
	ValueID *strfmt.UUID `json:"value_id"`
}

// Validate validates this story custom field
func (m *StoryCustomField) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFieldID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateValue(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateValueID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *StoryCustomField) validateFieldID(formats strfmt.Registry) error {

	if err := validate.Required("field_id", "body", m.FieldID); err != nil {
		return err
	}

	if err := validate.FormatOf("field_id", "body", "uuid", m.FieldID.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *StoryCustomField) validateValue(formats strfmt.Registry) error {

	if err := validate.Required("value", "body", m.Value); err != nil {
		return err
	}

	return nil
}

func (m *StoryCustomField) validateValueID(formats strfmt.Registry) error {

	if err := validate.Required("value_id", "body", m.ValueID); err != nil {
		return err
	}

	if err := validate.FormatOf("value_id", "body", "uuid", m.ValueID.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this story custom field based on context it is used
func (m *StoryCustomField) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *StoryCustomField) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StoryCustomField) UnmarshalBinary(b []byte) error {
	var res StoryCustomField
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
